### ISSUE TITLE
Word-cloud Generator

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#10]
## Script Title - Create a word cloud. Good for NLP visualizations

**what will change** - Adding a script of the word cloud

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by abhinand5** [comment]
Can I also do this?

**Comment by pawangeek** [comment]
Sure but make a PR of first, then I will assign this to you :)

**Comment by fieryash** [comment]
Can I work on this too?

**Comment by pawangeek** [comment]
Sure why not @fieryash
