### ISSUE TITLE
File Sorter made in Python

### ISSUE THREAD

**Issue by HemanthTenneti** [python-geeks/Automation-scripts#1003]
## File Sorter -

Hey! I wanted to add one of my projects that I'm proud of, which automates sorting files in your windows machine. I've dealt with messy folder and incomprehensible folder structure for a long time in my life so I decided to make this project. This program of mine, has a very small and minimalistic interface I've made using tkinter, and has simple buttons that are very self-explanatory and they sort all the files in the folder you've chosen.

## Instructions - 

- Ask what folder to choose in the user's machine.
- Run a sorting function based on extensions
- Sort each file into a dedicated folder of it's own
- Allow terminal sorting command for quicker sorting.

### Programming Languages

- Python

**Comment by pawangeek** [comment]
Hey @HemanthTenneti is this is similar to #220?

**Comment by HemanthTenneti** [comment]
Yes, my bad. I didn't realize that there was a file sorting program already as there were no folders matching the keyword "sort".
You can close this now.
