### ISSUE TITLE
Convert word to PDF

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#109]
## Script Title - Script is able to convert doc file to pdf file

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by fieryash** [comment]
can i do this?

**Comment by pawangeek** [comment]
okay sure
