### ISSUE TITLE
Twitter Bot

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#11]
## Script Title - Add a bot that tweets for me. One can use "tweepy" for that

**what will change** - Adding a script for creating a twitter bot

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by ashkankamyab** [comment]
Hi,
I would like to work on such tasks. would you mind if I work on this ?

I am also considering what would be your preference end point? would you like a `cli-interface` which tweets?
@pawangeek

**Comment by pawangeek** [comment]
Yeah, sure go ahead. And moreover, you can use any o-auth library and endpoints are like /update_status, /user_timeline, and /login. You can add more beyond that too :)
