### ISSUE TITLE
Password manager

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#111]
## Script Title - Script should able to store passwords

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by ebsa491** [comment]
Hi, Can you assign it to me? thanks

**Comment by ebsa491** [comment]
Hi, can you assign it to me? thanks

**Comment by pawangeek** [comment]
Sure go-ahead
