### ISSUE TITLE
Image Annotator

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#113]
## Script Title - Script to able to add proper annotations if an image is given

**what will change** - Adding script

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by SaiSrichandra** [comment]
Hey, I would like to try it out

**Comment by pawangeek** [comment]
okay, try it out. In any case or clarification, just ping me

**Comment by SaiSrichandra** [comment]
How do you want it to work
Like what are the inputs and outputs
Is there any already existing library you know of or should I have to use a machine learning model

**Comment by pawangeek** [comment]
No there is not any Library of this I think, But there are many APIs of the same. But I encourage you to create your own weights save them in a pickle file and call them in the script (As tag suggest deep-learning) :)

**Comment by SaiSrichandra** [comment]
Making sure we are on the same page,
You mean image captioning right
Like you give an image and it gives out few words of objects it identifies right?
Or is there any other idea

**Comment by pawangeek** [comment]
Yes that's what I want, Description of image

**Comment by pawangeek** [comment]
Hey @SaiSrichandra still trying to do that ??

**Comment by SaiSrichandra** [comment]
yeah couldn't find a good way though

**Comment by SaiSrichandra** [comment]
I can just give names of objects in the picture simply
But making it into a sentence, couldn't figure that out

**Comment by pawangeek** [comment]
okay, I think @Anustup900 can handle this?

**Comment by Anustup900** [comment]
Yes I can handle this , can it be assigned @pawangeek

**Comment by pawangeek** [comment]
Thanks @Anustup900

**Comment by pawangeek** [comment]
@Anustup900 any progress regarding same?

**Comment by Anustup900** [comment]
Yes i am uploading the code by  tonight by removing the liniting errors @pawangeek
