### ISSUE TITLE
Removing watermark from scanned documents

### ISSUE THREAD

**Issue by fieryash** [python-geeks/Automation-scripts#117]
## Script Title -Script to remove watermark scanned documents 

**what will change** - adding code

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by fieryash** [comment]
Can you assign me this? Does it count towards hacktoberfest?

**Comment by pawangeek** [comment]
Yes, it will, and it's a good script too but can you brief about what kind of watermark is it?

**Comment by fieryash** [comment]
Basically we use cv2 to remove the watermark from any sort of scanned documents

**Comment by fieryash** [comment]
![test](https://user-images.githubusercontent.com/48550799/95582102-c5afd700-0a57-11eb-9343-514cc24ee377.jpg)

something like this.. we can remove the watermark which can be useful when an OCR or something is used on the document to extract text

**Comment by fieryash** [comment]
![Word-2016-draft-watermark](https://user-images.githubusercontent.com/48550799/95582257-07d91880-0a58-11eb-8db8-f167df58ab07.png)

basically removing watermark from such documents, useful if in further steps an OCR is used to read the text

**Comment by pawangeek** [comment]
Okay, that's fine. so it's pdf/doc or any other format?

**Comment by fieryash** [comment]
jpg format.. but i can extrapolate to pdf if needed

**Comment by pawangeek** [comment]
okay do it for jpg and extend it further using pdf2image for pdfs

**Comment by fieryash** [comment]
It is done
