### ISSUE TITLE
Linkedin Connection scraper

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#119]
## Script Title - script should able to scrap all connections of one who is running that script
(can be done by requests/selenium/bs4 )

**what will change** - Adding script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by GoluffyxD** [comment]
Hey, Id like to take this issue.

**Comment by pawangeek** [comment]
Okay, sure :)

**Comment by GoluffyxD** [comment]
Hey! Turns out Scraping on LinkedIn isn't permitted according to the Terms and Conditions! 
I'm afraid Ill have to discontinue! Sorry about that

**Comment by pawangeek** [comment]
Yeah, I recently got to know that. Thanks for your step and aware all of us about the same :). Looking forward to you for coming up a different scraper maybe like getting facebook data using APIs
