### ISSUE TITLE
Encrypt PDF

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#12]
## Script Title - Encrypt pdf by using any hash algorithm

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by jp2373** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by pawangeek** [comment]
Sure, go ahead

**Comment by SoumyaRanjanNaik** [comment]
Could you please clarify if we need to just password protect the pdf file or use a script to encrypt the file directly (which would require anither decryption script) using some algorithm like AES ?

**Comment by pawangeek** [comment]
We have to encrypt the pdf file using any algorithm(aes, rsa, etc. ). And able to decrypt that later

**Comment by SoumyaRanjanNaik** [comment]
okay! Could you please assign this to me ? I would like to work on it.

**Comment by pawangeek** [comment]
Sure, why not
