### ISSUE TITLE
Website blocker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#122]
## Script Title - script able to block user-requested website

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by GaganSingh5** [comment]
hey dev @pawangeek  I would like to work on this!!!

**Comment by pawangeek** [comment]
Okay go ahead @GaganSingh5
