### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#123]
## Script Title - Script is able to play and pause (one can use cv2 and ffpyplayer)

**what will change** - Adding script of Video Player

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by DragonGhost7** [comment]
I could do this.

**Comment by pawangeek** [comment]
ok, go-ahead  @DragonGhost7
