### ISSUE TITLE
Screen recorder

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#126]
## Script Title - Should have play, pause and end args in recorder
 
**what will change** - adding a script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by senguyen1011** [comment]
I'm interested in working on this, could I be assigned to it?

**Comment by pawangeek** [comment]
sure, go ahead :)
