### ISSUE TITLE
Quick paint application

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#127]
## Script Title - It should be useful for creating quick notes somewhere

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Lunaditu** [comment]
hey, can i take this?

**Comment by pawangeek** [comment]
sure
