### ISSUE TITLE
Auto complete

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#13]
## Script Title - Create auto-completion using either bigram/n-grams or trie data-structure

**what will change** - Adding auto-completion script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by abhinand5** [comment]
Can you assign this to me?

**Comment by pawangeek** [comment]
sure, go ahead
