### ISSUE TITLE
Events notification (FB to WhatsApp)

### ISSUE THREAD

**Issue by shubhampawar** [python-geeks/Automation-scripts#132]
## Script Title -

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by pawangeek** [comment]
This seems to be fine. Go ahead and send a PR for this
