### ISSUE TITLE
Digital Clock

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#134]
## Script Title - Create a digital clock using any GUI in Python

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Xerdiosa** [comment]
I'd like to work on this, can you assign me for this issue?

**Comment by pawangeek** [comment]
Okay sure

**Comment by johan7004** [comment]
i would like to work on this can you assign me ?

**Comment by pawangeek** [comment]
okay @johan7004 go ahead

**Comment by SunTzunami** [comment]
I'd be grateful if you could assign me for this issue.

**Comment by pawangeek** [comment]
Hey @SunTzunami, it's already assigned to two members. Kindly look at other issue and check if you're able to solve them

**Comment by SunTzunami** [comment]
The thing is I've already made it. 😅

**Comment by pawangeek** [comment]
Then doing the same thing, again, isn't add any value I think. Come up with something new, something real

**Comment by SunTzunami** [comment]
Like I made it right now.

**Comment by SunTzunami** [comment]
I was working on arcade framework earlier. This was new to me.

**Comment by TheFenrisLycaon** [comment]
I can do this !

**Comment by johan7004** [comment]
i have created a digital clock using tkinter

**Comment by johan7004** [comment]
i am not able to commit, new to github. kindly help

**Comment by pawangeek** [comment]
Here you go @johan7004 https://opensource.com/article/19/7/create-pull-request-github

**Comment by johan7004** [comment]
thanks

**Comment by pawangeek** [comment]
hey @johan7004 are you able to find process?

**Comment by pawangeek** [comment]
@TheFenrisLycaon can you complete this?

**Comment by TheFenrisLycaon** [comment]
Sure can @pawangeek

**Comment by TheFenrisLycaon** [comment]
@pawangeek done !! Please review and merge.
