### ISSUE TITLE
Stopwatch

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#136]
## Script Title - With features start, stop and reset

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by durgeshahire07** [comment]
hello, i want to contribute to this project can you assign this issue to me

**Comment by pawangeek** [comment]
okay sure
