### ISSUE TITLE
Domain availability checker (DNS lookup)

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#138]
## Script Title - Script is able to check the domain is available or not

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by pwees** [comment]
I'll take this one.

**Comment by pawangeek** [comment]
Ok fine

**Comment by aolaria** [comment]
Hi, I've already figure it out this one, but I've forgotten to ask for assignation. there's still a chance? thanks!
