### ISSUE TITLE
Voice Recorder

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#139]
## Script Title - Script is able to record voice (Play, pause, done functionalities)

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by SaiSrichandra** [comment]
I would like to give this a shot
I already have a basic player without  a pause button 
I will try to implement  the pause button

**Comment by pawangeek** [comment]
Okay go ahead :)
