### ISSUE TITLE
Automate Birthday Wish

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#140]
## Script Title - Send a message on any social platform at 12.01

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by pawangeek** [comment]
@ashkankamyab will you try to figure this out? And social media can be Fb/telegram

**Comment by ashkankamyab** [comment]
> @ashkankamyab will you try to figure this out? And social media can be Fb/telegram

Hi,
Yeas. Please assign it to me :-)

**Comment by ashkankamyab** [comment]
@pawangeek My [PR](#270) crashed. May you please give me a hand to resolve this ?

**Comment by m4dummies** [comment]
Hello, 
Can this be assigned to multiple people ? 
I am ready to do this.
Thanks :)

**Comment by pawangeek** [comment]
Yes @m4dummies but you have to do this for Facebook since he is doing for telegram

**Comment by m4dummies** [comment]
> Yes @m4dummies but you have to do this for Facebook since he is doing for telegram

Hi Pawangeek I managed to write the script...but how do commit the folder in the repo, can u help me with that?

**Comment by pawangeek** [comment]
> > Yes @m4dummies but you have to do this for Facebook since he is doing for telegram
> 
> Hi Pawangeek I managed to write the script...but how do commit the folder in the repo, can u help me with that?

There is a link in README to do that. Further, it's an easy process just fork the repo-add folder by git bash in own repo and then make a pull request
