### ISSUE TITLE
Setup venv Script

### ISSUE THREAD

**Issue by Sacrezar** [python-geeks/Automation-scripts#143]
## Setup venv Script 

**what will change:** Add a script to setup a venv and install packages in requirement.txt for all scripts in folders . 

I also suggest to add a gitignore. 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python or Bash

Happy Coding,

**Comment by nagy3n** [comment]
In bash or python?

**Comment by Sacrezar** [comment]
If it was me, I would have done it in bash. But I'm not the repo owner. So gotta ask @pawangeek if the issue is accepted 😊

**Comment by pawangeek** [comment]
Okay that’s fine to do this in bash @nagy3n would you like to take this ?

**Comment by fa1l** [comment]
I can do this

**Comment by pawangeek** [comment]
Ok go ahead
