### ISSUE TITLE
Covid-19 tracker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#148]
## Script Title - A script able to retrieve data about coronavirus

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by edoardottt** [comment]
Done
