### ISSUE TITLE
PDF Editor

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#158]
## Script Title - Script should be able to edit pdf
 
**what will change** - Adding a script 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by funbeedev** [comment]
Hi there,

Can this be assigned to me?

**Comment by pawangeek** [comment]
Sure :)

**Comment by funbeedev** [comment]
Thanks, I'll start working on it

**Comment by pawangeek** [comment]
any update @funbeedev

**Comment by funbeedev** [comment]
Hi, I'll have a pull request issued today

**Comment by funbeedev** [comment]
Pull request is now sent. Any feedback is welcome.
