### ISSUE TITLE
Youtube Video Downloader

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#159]
## Script Title - Script should be able to download YT videos

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by LucasVanHaaren** [comment]
Hi, I'm up to developing this script ! :point_up:

Is it possible to use third party libraries like [pytube](https://github.com/nficano/pytube)?

**Comment by pawangeek** [comment]
okay, that's fine but make the process smooth as possible and add args for triggering script :)
