### ISSUE TITLE
Image Cartoonizer

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#160]
## Script Title - Script is able to convert any image to cartoon character

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Anustup900** [comment]
please assign this to me

**Comment by pawangeek** [comment]
okay fine @Anustup900
