### ISSUE TITLE
Text from Image Extractor

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#162]
## Script Title - Script is able to extract text from image

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by jp2373** [comment]
Just finished working on it, can I create a PR?

**Comment by pawangeek** [comment]
sure :)
