### ISSUE TITLE
Tweet-cli script

### ISSUE THREAD

**Issue by ashkankamyab** [python-geeks/Automation-scripts#163]
## Script Title - Tweet using tweet-cli

**what will change** - Add script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by ashkankamyab** [comment]
@pawangeek 
May you please approve this? I would like to grab it as well if you don't mind.

**Comment by pawangeek** [comment]
Okay go ahead, but can you brief me about exact objective and how you gonna achieve that

**Comment by ashkankamyab** [comment]
> Okay go ahead, but can you brief me about exact objective and how you gonna achieve that

Thanks.
The Objective is to tweet in a nerdy way :monkey_face: using cli like `tweet-cli "this is my tweet from tweet-cli"` 
This is a super easy task as we have implemented the tweet API module. So I just call this module and update the status using `api.update_status()` . Please share your idea enhancement if you have some.

besides I have a question. The Dockerfile also needs to be revised, would it be fine If i fix it within this issue or you want me to open a new issue for it ?

**Comment by pawangeek** [comment]
Sounds great and fix that dockerfile in this same issue. I think no need to open another one
