### ISSUE TITLE
Take a picture of person unlocking the laptop and email it with location.

### ISSUE THREAD

**Issue by shubhampawar** [python-geeks/Automation-scripts#164]
## Script Title - 

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by pawangeek** [comment]
Sorry can you describe more about it ?
