### ISSUE TITLE
HTML to pdf

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#171]
## Script Title - the script is able to convert HTML to pdf

**what will change** - adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by maheshschand** [comment]
Can you please assign this issue to me?

**Comment by pawangeek** [comment]
okay sure :)

**Comment by maxily1** [comment]
Could you assign this issue to me?

**Comment by maxily1** [comment]
Oh nvm, It's been done already.

**Comment by maheshschand** [comment]
@pawangeek It's done already.

**Comment by pawangeek** [comment]
oh my bad I haven't look at that @maheshschand
