### ISSUE TITLE
Speet Tester

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#172]
## Script Title - script able to test the speed of connectivity/internet

**what will change** - adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by LucasVanHaaren** [comment]
Hi, I would like to work on it !

**Comment by pawangeek** [comment]
Can you please make a PR of the previously assigned one first?

**Comment by mateuszkowalke** [comment]
Hello. I'd like to tackle this one if possible?

**Comment by pawangeek** [comment]
okay, go-ahead @mateuszkowalke
