### ISSUE TITLE
Instagram Follower utility

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#173]
## Script Title - Script should able to find persons who don't follow you, but you follow them (look at instapy library for help)

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by RIstiaque** [comment]
I'd like to attempt this, can you assign this to me?

**Comment by pawangeek** [comment]
sure @RIstiaque , it's the most interesting task I've created till now :). Hope you understand by description what you have to do in this.

**Comment by maxily1** [comment]
Hey could you assign me?

**Comment by pawangeek** [comment]
Okay try to come up with one @maxily1

**Comment by maxily1** [comment]
Is it normal if I won't be using instapy?
Unfortunately it doesn't work properly for me.

**Comment by pawangeek** [comment]
Yup, you can use any lib/tool, but it will able to solve end-purpose
