### ISSUE TITLE
Image Resizer

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#175]
## Script Title - Should pop error message when trying to expand and works when trying to compress

**what will change** - Adding acript

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by happyeric77** [comment]
I am now doing python image task, might I try to work on it?

**Comment by pawangeek** [comment]
umm, okay @happyeric77 go ahead
