### ISSUE TITLE
Subtitle Creator

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#176]
## Script Title - One can use moviepy for this purpose

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by DragonGhost7** [comment]
I can take this issue

**Comment by pawangeek** [comment]
okay, go-ahead

**Comment by pawangeek** [comment]
hey, @DragonGhost7 any update?

**Comment by DragonGhost7** [comment]
Yes, I finished, linking the pull request now.
