### ISSUE TITLE
Keylogger

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#178]
## Script Title - As the name suggests, it should able to record keys (Can be sone by pynput)

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by thevirtualbuddy** [comment]
Can I take this issue?

**Comment by pawangeek** [comment]
sure, go-ahead

**Comment by thevirtualbuddy** [comment]
Okay! Thank you @pawangeek

**Comment by thevirtualbuddy** [comment]
Hello, @pawangeek!
Could you please tell me how to pass the codespell test and flake8linter test? I'm a newbie here.

**Comment by thevirtualbuddy** [comment]
Hi @pawangeek !
I installed code spell checker extension on my vscode and it is showing warning because of the module pynput. 
Any solution on how to remove the warning and get all the checks passed?

**Comment by thevirtualbuddy** [comment]
@pawangeek Please check PR #184 .
