### ISSUE TITLE
Duplicate File checker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#18]
## Script Title - Able to find duplicate files in a folder

**what will change** - Adding duplicate finder script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by varuntumbe** [comment]
I can do this. assign it to me
Thanks in advance

**Comment by pawangeek** [comment]
Yeah sure :)

**Comment by pawangeek** [comment]
hey @varuntumbe, any progress?

**Comment by varuntumbe** [comment]
i tried to do it by just comparing the name then it hit me its more elegent to check it using size and also i have learnt that by hashing a content it would be more perfect so still working.

when's the deadline ?

**Comment by pawangeek** [comment]
okay that's cool, no not any strict deadline, just carry on :)

**Comment by varuntumbe** [comment]
Hey one last question i havent changed contributors file. do i have to change it to include mine ?
thanks in advance

**Comment by pawangeek** [comment]
Wait I will add you
