### ISSUE TITLE
Video merger 

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#180]
## Script Title - Script is able to merge two videos

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by DragonGhost7** [comment]
When you say merge, do you mean concatenate one after another, or how?

**Comment by pawangeek** [comment]
Merged is something including your changes in the main repository

**Comment by DragonGhost7** [comment]
yes i know, i mean what exactly should this script do with a video

**Comment by pawangeek** [comment]
ahh, okay here merging means adding two videos, yes that's concatenating. Then we make another different Issue to do that in parts too like it's able to add clips in between. 

Currently, it's a simple concatenation

**Comment by DragonGhost7** [comment]
ay, okey, i could do that

**Comment by pawangeek** [comment]
Okay, cool

**Comment by pawangeek** [comment]
Hey, @DragonGhost7 any updates ?

**Comment by DragonGhost7** [comment]
Done, created pull request
