### ISSUE TITLE
Mini Plagiarism Checker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#181]
## Script Title - One can use NLP stuff with google APIs (Just remove credentials before sending PR)

**what will change** - Adding script

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by abhinand5** [comment]
I can do this as well if assigned.

**Comment by pawangeek** [comment]
okay but do the first one first

**Comment by abhinand5** [comment]
Can you assign me now?

**Comment by pawangeek** [comment]
yaaa, you deserve this now :)

**Comment by m4dummies** [comment]
Hi @pawangeek can u explain what needs to be done here?
