### ISSUE TITLE
Files in proper folder

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#19]
## Script Title - Able to add files automatically in the desired folders

**what will change** - Adding Script of file arranger

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by Kirkkm** [comment]
Hello, I have done something similar like this for a custom logger I created for my Discord/Twitch bots. I would like to give this a try. Thanks!

**Comment by pawangeek** [comment]
Okay go ahead, I will review your PR

**Comment by pawangeek** [comment]
hey @Kirkkm, any update ?

**Comment by Kirkkm** [comment]
Hey @pawangeek, I have started writing the script on my local machine but I got busy with work the past few days. I plan to continue to work on it tonight since I will have more free time to dedicate to this.

**Comment by pawangeek** [comment]
That's alright no problem. You can do this in your free time maybe at weekend or so
