### ISSUE TITLE
Audio Recorder

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#198]
## Script Title - As the name suggests, the script is able to record audio with a start, pause, and complete functionality

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by durgeshahire07** [comment]
hello @pawangeek , i am interested in doing this task can you assign me this issue?

**Comment by pawangeek** [comment]
cool

**Comment by durgeshahire07** [comment]
is it audio recorder or video recorder?

**Comment by pawangeek** [comment]
Audio recorder

**Comment by durgeshahire07** [comment]
okay

**Comment by durgeshahire07** [comment]
hello @pawangeek can i add recorder with play and stop functionality, later on can you create different issue for adding pause and resume functionality in the code?

**Comment by pawangeek** [comment]
OKay that's fine
