### ISSUE TITLE
Video to gif convertor

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#20]
## Script Title - Convert video with extension(.mkv, .mp3 etc.) to .gif

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by javmarina** [comment]
Can you assign it to me?

**Comment by pawangeek** [comment]
Sure, I will but create a pull request of previous issue first :)
