### ISSUE TITLE
Port Scanner

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#201]
## Script Title - Able to scan ports

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by roterhut** [comment]
Hi,
Can I work on this?

**Comment by corleone77** [comment]
Hi, I'd like to contribute on this issue.
I've created the script right now.
I'm ready for make the PR.
Thanks.

**Comment by corleone77** [comment]
Hi @pawangeek ,
Thanks ¡¡¡ ;)

**Comment by pawangeek** [comment]
Expecting a star on repo by you, @corleone77 😃

**Comment by corleone77** [comment]
> Expecting a star on repo by you, @corleone77
Done ¡¡¡¡
