### ISSUE TITLE
Wikipedia Search

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#202]
## Script Title - Simple and easy only for beginners. One has to add functionality to save the search as PDF too

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by thevirtualbuddy** [comment]
Functionalities required:
1. Search query in wikipedia.
2. Save the result as pdf.

Am I right?
If the above functionalities is sufficient for this isssue, can you assign it to me?

**Comment by pawangeek** [comment]
See you have to save the partial content of the first search results. Like if we query Indian premier league. It will save the initial abstract of the article about IPL (excluding images)

**Comment by thevirtualbuddy** [comment]
Okay @pawangeek got it. :)

**Comment by thevirtualbuddy** [comment]
Hi, @pawangeek!
Please have a look at the PR #226 :)
Thank you.
