### ISSUE TITLE
Text summarizer

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#203]
## Script Title - Very tough and challenging one. One can use BERT/ cosine dist to solve this and no need to be 100% correct. Just make a simple prototype :). For more comment in the issue 

**what will change** - Adding script

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by ferhah** [comment]
Hm, sounds complex, but intersting. I would like to give it a try.

**Comment by pawangeek** [comment]
Sure, give it a try, no need to worry that it should work perfectly. Up to 50/60 is a pretty good score :)

**Comment by tenzu15** [comment]
Can I give it a try?

**Comment by ferhah** [comment]
Hi @tenzu15, I already start working on it. So, it might be better if I continue working on it.

**Comment by tenzu15** [comment]
Sure, No Problem
