### ISSUE TITLE
Converting sound/voice to text

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#21]
## Script Title - Able to convert sound to its text. Can be done using "librosa" library

**what will change** - Adding script of voice_to_text convertor

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Saumya-Mishra9129** [comment]
@pawangeek Can you assign this to me?

**Comment by pawangeek** [comment]
Okay go ahead :)

**Comment by Anustup900** [comment]
Hey I want to contribute in this i also proceeded with the code can you please add me up

**Comment by pawangeek** [comment]
Hello @Anustup900, this issue is assigned to @Saumya-Mishra9129. Can you do the reverse of that? I mean from text to sound ??

**Comment by Anustup900** [comment]
> Hello @Anustup900, this issue is assigned to @Saumya-Mishra9129. Can you do the reverse of that? I mean from text to sound ??

Yes I can ,please assign it to me , am on it

**Comment by pawangeek** [comment]
Sure @Anustup900  Just comment on this #50 and I will assign this to you

**Comment by Anustup900** [comment]
> Sure @Anustup900 Just comment on this #50 and I will assign this to you

Done

**Comment by pawangeek** [comment]
hey, any update @Saumya-Mishra9129

**Comment by Crowfunder** [comment]
Hello @pawangeek ,
Wouldn't it be simpler to use PocketSphinx library for voice recognition instead? If it'll do you can assign this issue to me.

**Comment by pawangeek** [comment]
@Crowfunder I think it's for live voice recognition, isn't it? I m assigning this to you come up with a solution :)
