### ISSUE TITLE
Simple Book Manager

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#211]
## Script Title - Create a DB to store which(name) book is placed with its path and subject of that book. Bonus if you able to add some kind of GUI to handle that

**what will change** - Adding the script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by GoluffyxD** [comment]
Hey! I'd like to work on this issue! Can you assign it to me?

**Comment by pawangeek** [comment]
@GoluffyxD any update?

**Comment by GoluffyxD** [comment]
@pawangeek I'm done with the script. Working on GUI implementation now. Should be able to finish it in a few days.

**Comment by pawangeek** [comment]
Ahh, okay no problem
