### ISSUE TITLE
video watermarker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#212]
## Script Title - Able to add watermark in the video

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by maxily1** [comment]
Hey, I'd like to work on this one!
Please assign me :)

**Comment by pawangeek** [comment]
Okay fine @maxily1

**Comment by maxily1** [comment]
The watermark should be a text?

**Comment by pawangeek** [comment]
yeah, that's enough for now but if it's possible to add something unique like the user is able to choose multiple fonts (at least 4-5) +  weight + size( just add range). 

Is that possible @maxily1
