### ISSUE TITLE
Medium article Downloader 

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#213]
## Script Title - Able to download the medium article and save them as PDF(with images if possible) if no blocker else raise an error 

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by tenzu15** [comment]
I would like to give it a try, could you assign it to me?

**Comment by pawangeek** [comment]
okay go ahead @tenzu15

**Comment by pawangeek** [comment]
@tenzu15 any update?

**Comment by tenzu15** [comment]
> @tenzu15 any update?

Found useful things, working on it.

**Comment by pawangeek** [comment]
Cool keep working 👍

**Comment by funbeedev** [comment]
Hi, Can I take this one?

**Comment by pawangeek** [comment]
Sure @funbeedev

**Comment by vivekascoder** [comment]
Hey, can i work on this?

**Comment by vivekascoder** [comment]
@pawangeek  I send a PR for this task please check.

**Comment by funbeedev** [comment]
I've submitted my PR for this. Feedback is welcome.
