### ISSUE TITLE
Torrent Searcher

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#214]
## Script Title - Able to search on torrent

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by corleone77** [comment]
Hi @pawangeek 
Can I try it ¡¡¡
Thanks.

**Comment by HolgerDoerner** [comment]
Hello, I would take this one for HacktoberFest :smiley:

**Comment by pawangeek** [comment]
okay, @HolgerDoerner go ahead :)
