### ISSUE TITLE
Image Encrypter

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#215]
## Script Title - Able to encrypt+decrypt images 

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by egurnick** [comment]
Hi, I'd like to work on this

**Comment by pawangeek** [comment]
okay that's cool you can take help from #12

**Comment by egurnick** [comment]
It looks like there is already a script that is a part of this project called PdfEncrypt that can encrypt any file type. How should I proceed?

**Comment by pawangeek** [comment]
Ohh, I don't read your PR completely, my bad
