### ISSUE TITLE
Face mask detector

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#216]
## Script Title - Quick example to solve the purpose

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by abhinand5** [comment]
Hi, can you assign this to me?

**Comment by pawangeek** [comment]
okay sure

**Comment by keshav340** [comment]
can you assign this to me?
