### ISSUE TITLE
File arranger

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#219]
## Script Title - Files arranged according to extension in respective folders

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by ebsa491** [comment]
Hey @pawangeek, can I work on it?

**Comment by TheFenrisLycaon** [comment]
I can do it

**Comment by pawangeek** [comment]
Hey @ebsa491 we should give a chance to first contributors :) hope you understand. And @TheFenrisLycaon go ahead with this

**Comment by ebsa491** [comment]
> Hey @ebsa491 we should give a chance to first contributors :) hope you understand. And @TheFenrisLycaon go ahead with this

Yes you right, sure.

**Comment by TheFenrisLycaon** [comment]
Alright.
