### ISSUE TITLE
Price alert

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#22]
## Script Title - Alert price drop of a product from Amazon/Flipkart or any similar ecom site

**what will change** - Adding price alerter

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by ashkankamyab** [comment]
Hi 
I have already worked on the same thing(just amazon). I can share my solution here. Would it be fine ?

**Comment by pawangeek** [comment]
Okay fine

**Comment by ashkankamyab** [comment]
### I am almost finished with task but I need consultation:

Questionnaires: 

- Twillio for sending SMS as notification tested, but it is not free. Do we have any equivalent for free?
- What shoudl be the Margin of the reduction to send a notification. At the moment I need to implement this and I have some Idea:

- [x] Current Price reduced 20% than Highest Price.
- [x] Current Price is equal/smaller than historic lowest Price.

All suggestions are well come. 
@pawangeek

**Comment by pawangeek** [comment]
i) Twilio is sending SMS for free if you insert any verified number there, just doing that is enough or rather you can use SendGrid as an alternative for Emailing instead of SMS

ii) If the price comes down from the target price
