### ISSUE TITLE
Games ?

### ISSUE THREAD

**Issue by TheFenrisLycaon** [python-geeks/Automation-scripts#222]
## Script Title - Games made with Tkinter and PyGame

**what will change** - Add new files

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

Happy Coding,

**Comment by TheFenrisLycaon** [comment]
@pawangeek I have made games on python. Is this a good place to share ?

**Comment by pawangeek** [comment]
sorry @TheFenrisLycaon currently we're not accepting any games. As the name suggests this repo is for automation tools only
