### ISSUE TITLE
Torrent Searcher help

### ISSUE THREAD

**Issue by alvinuday** [python-geeks/Automation-scripts#225]
## Where you stuck - I don't really understand what is required by us
(what are we supposed to do )

**Frankly ask your question (We're also in learning phase :p )**
I do get you need to use python , but what do we need to code for .
## What you want to do?
Its kind of my first time ,so i dont understand whats required of me , instructions are not that clear

## Any other remark/screenshot etc.

**Comment by pawangeek** [comment]
you have to make something, which is able to search "movie" (input by the user) on torrent

**Comment by maxily1** [comment]
You could use web scraping in Python or use the unofficial TPB api. (https://pypi.org/project/ThePirateBay/)
