### ISSUE TITLE
Update pdf_encrypt code

### ISSUE THREAD

**Issue by am401** [python-geeks/Automation-scripts#229]
## Script Title -

**what will change** - Looking to update the existing *pdf_encrypt* application to amalgamate the separate *PdfEncrypt.py* and *PdfDecrypt.py* files 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [] Adding New Code
- [x] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by am401** [comment]
Hello there - I would like to look at updating the above application in order to create one single application to encrypt and decrypt functionality. Please assign this task to me if possible to work on.

**Comment by pawangeek** [comment]
Okay, that's fine to go ahead and try to use argparse lib too, to trigger completely from the terminal, no need to prompt the password section in between.

**Comment by am401** [comment]
Hey @pawangeek - thank you very much. I also thought about adding the ability to define or set a flag for the password but that has the potential of logging in plain text within the shell history what the password is. My current thoughts are that the user will still be prompted for the password in order to prevent revealing it using the above method

**Comment by pawangeek** [comment]
Okay, your argument seems to be correct, fine continue with the prompt for the password
