### ISSUE TITLE
Email sender

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#23]
## Script Title - Send an email on one's behalf

**what will change** - Adding email-sender script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by ashkankamyab** [comment]
Hi, 
I would like to work on this, would you mind assign it to me?

**Comment by pawangeek** [comment]
Sure I will, but you send PRs to previously assigned issues :)

**Comment by sculley** [comment]
Hello,

I would like to work on this if possible?

**Comment by pawangeek** [comment]
Okay meanwhile I assign this to you @sculley

**Comment by ashkankamyab** [comment]
> Sure I will, but you send PRs to previously assigned issues :)

Sure. No Problem.

**Comment by pawangeek** [comment]
hey @sculley any progress ?

**Comment by sculley** [comment]
> hey @sculley any progress ?

Yes sir, I have all the code working/PEP8 validated. I am working on the README.md right now and will submit the PR later today :+1:

**Comment by pawangeek** [comment]
Arey, don't call me Sir, I m just a learner like you :)
