### ISSUE TITLE
We need Testers

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#232]
We need some volunteers to check that each and every script is working properly, It's a yearlong thing, so no need to be in a hurry. You can do that in your spare time too.

**Comment by maxily1** [comment]
I'd like to help!
But will there by any system in which we can tick which script was checked and is working?

**Comment by pawangeek** [comment]
yes, we can label them tested

**Comment by maxily1** [comment]
Alright, thanks, Then I'd like to help!

**Comment by pawangeek** [comment]
Okay, I am adding you as maintainer, this is a year-long task, not just for hacktober, hope you will collaborate accordingly :)

**Comment by maxily1** [comment]
I will :)

**Comment by maxily1** [comment]
I think we should open an issue which is open only for the testers, and then we will write the name of the folder tested, and will write summary.

**Comment by pawangeek** [comment]
Ahh no need to open a new issue, just mention errors in the same closed PR and label them as bug otherwise label them as tested if not have any error

**Comment by Sacrezar** [comment]
Hello, I'd like to help too if you don't mind!

**Comment by pawangeek** [comment]
Sure, why not @Sacrezar . I'm eagerly waiting for your comment btw 😃

**Comment by Sacrezar** [comment]
Well, You're putting a lot of pressure on me 😄

**Comment by Sacrezar** [comment]
If we see any error and are able to correct it, can we?

**Comment by pawangeek** [comment]
Yes, that's the main responsibility for as a tester

1) Test scripts locally and remove any kind of bug (try to catch all exception)
2) Include any missing point in README
3) Check requirements.txt file

GO straight with 2 and 3 points and make a PR for 1st.

**Comment by pawangeek** [comment]
And add a testing label when you pick any script, to avoid collisions

**Comment by Sacrezar** [comment]
It's fine yes 🙂

In this case, shouldn't we also work on the issue #238?

**Comment by Sacrezar** [comment]
Okay my bad 👌

**Comment by maxily1** [comment]
Sure @pawangeek :D

**Comment by pawangeek** [comment]
Guys if you see any major error or if any script is showing unexpected behavior report that it with REPORT a BUG under issues template, else it sends notifs to the author of that PR
