### ISSUE TITLE
Certificate Generator

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#235]
## Script Title - This is for contributors, We have to generate a certificate for all contributors in appreciation for their contribution to automation script and hactoberfest. 

**what will change** - Adding a script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by ashwanimehra** [comment]
hey @pawangeek , i want to work on this issue, can u assign me?

**Comment by pawangeek** [comment]
Sure go ahead, can you have any design or idea of the design for certificate

**Comment by ashwanimehra** [comment]
I was thinking of using one of the templates on MS-Word, if you have any specific requirements, I'm all ears.

**Comment by pawangeek** [comment]
![cert](https://user-images.githubusercontent.com/42181691/95756893-04e26000-0cc4-11eb-9973-877d79a4c8a6.png)

Hey, is it possible to create one like this?

**Comment by pawangeek** [comment]
To extend it Lil bit, is it possible to deploy this mini web app on Heroku, netlify, or any other hosting platform (Free dyno)

**Comment by KKhushhalR2405** [comment]
Dear Maintainers,
I have successfully completed this issue, If you can assign it to me, I will make a PR.
Thank You.

You can check my work [here](https://github.com/KKhushhalR2405/Automation-scripts/tree/khushhalreddy/cartificate_generator).

**Comment by pawangeek** [comment]
wow @KKhushhalR2405 , Just one thing can you please turn it into a flask app that user just give the name in UI and it generates certificates 

And a few suggestions regarding that

- [ ] Remove option of xl, CSV file, the user just gives its name, pr and able to download the certificate by UI (I mean just use flask-wtf forms for taking input and output is generated certificate
- [ ] Optional -> If it's possible to use flask-sqlalchemy for that to store username, PR above (we have to use flask-admin too to view our user's database)
- [ ] optional -> the Last thing is to deploy it on Heroku (free-dyno) and use Heroku-Postgres in sqlalchemy orm.

I am ready to help you (if you wants) with this (So that we both learn together :) )

**Comment by KKhushhalR2405** [comment]
I started using Flask a week before, But I am sure I will come up with it in 2-3 days. 
Thank You

**Comment by pawangeek** [comment]
no problem @KKhushhalR2405 we have approx 10 days for this task, if you stuck somewhere in between just frankly ask for help.

**Comment by KKhushhalR2405** [comment]
Sure

**Comment by Vyvy-vi** [comment]
Isn't making that gonna just take a small pillow(PIL) script ?

**Comment by anujpatel224** [comment]
hey @pawangeek  can i also work on this?

**Comment by pawangeek** [comment]
> hey @pawangeek can i also work on this?

Okay fine @anujpatel224

**Comment by pawangeek** [comment]
> Isn't making that gonna just take a small pillow(PIL) script ?

want a full-fledged web app for that

**Comment by anujpatel224** [comment]
@pawangeek  thanks, so i have to make a complete app to generate the given type of cetificate right?

**Comment by pawangeek** [comment]
> @pawangeek thanks, so i have to make a complete app to generate the given type of cetificate right?

Yes try to do that with help of flask/django

**Comment by anujpatel224** [comment]
okay thanks

**Comment by m4dummies** [comment]
Hi @pawangeek , How are you doing. Could you please look into the contributors list whenever you can.

**Comment by jayanth1p** [comment]
> ## Script Title - This is for contributors, We have to generate a certificate for all contributors in appreciation for their contribution to automation script and hactoberfest.
> **what will change** - Adding a script for that
> 
> ## Instructions
> * Create a new folder for your script and file/folder name should be appropriate.
> * Create a README.md in your folder for program Instructions
> * add requirements.txt if needed
> 
> Please add/delete options that are not relevant.
> 
> * [x]  Adding New Code
> 
> ### Programming Language
> * [x]  Python
> 
> Happy Coding,
Hello, can you assign this work to me

**Comment by TheFenrisLycaon** [comment]
Is this done?

**Comment by pawangeek** [comment]
No @TheFenrisLycaon not yet

**Comment by TheFenrisLycaon** [comment]
I'd like to work on it.

**Comment by pawangeek** [comment]
Okay, @TheFenrisLycaon Go ahead. Let me know if you want any help

**Comment by shreyasvedpathak** [comment]
Is this still available? I'd want to get started on it. Also, if there is already work done, please let me know where I may pick it up. I notice you're looking for a flask web app. I have a lot of expertise with it and have previously done automated certificate generation. Please let me know what the intended outcomes are, and I'll be happy to help.

**Comment by pawangeek** [comment]
Hey @shreyasvedpathak you can pick the template, Idea is to create a simple Flask web app, if your input the name, It will generate the certificate. This will be our Ist iteration, we will add more features in next iterations

**Comment by shreyasvedpathak** [comment]
@pawangeek alright, I'll start right away.

**Comment by shreyasvedpathak** [comment]
hey @pawangeek, you haven't assigned me this yet, I'm almost done. Also, the flake8 thing, I am new to that, could you send some links that would help me get started.

Tech Stack:
Frontend: HTML, bootstrap 5
Backend: flask, PIL

**Comment by pawangeek** [comment]
You can create a PR new

**Comment by shreyasvedpathak** [comment]
hey, @pawangeek, I did a PR but it is not passing all the checks of flake8. It is showing me errors for the part of the code which has to be like that to prevent what we call "circular imports". You can below that, routes module is imported at the end and routes imported is not used, it has to be that way.
Check out this tutorial by Corey Schafer where he explains why it has to be that way [Python Flask Tutorial: Full-Featured Web App Part 5 - Package Structure](https://youtu.be/44PvX0Yv368?t=904)
![image](https://user-images.githubusercontent.com/68227226/130242032-a5478402-1947-49f3-875a-6c67e4aba6c3.png)

Please let me know how to proceed. I have passed all other checks.

**Comment by pawangeek** [comment]
Cool, @shreyasvedpathak I will review it and will if any changes requested
