### ISSUE TITLE
PDF watermarker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#236]
## Script Title - Should able to watermark pdfs

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Hardik0307** [comment]
@pawangeek want to work on this issue.

Kindly assign me.

**Comment by pawangeek** [comment]
Okay cool

**Comment by m4dummies** [comment]
Hi @pawangeek can you please assign this to me. 
Thanks

**Comment by m4dummies** [comment]
Hi @pawangeek I don't have any pending PRs. Can you assign me this one.

**Comment by pawangeek** [comment]
> Hi @pawangeek I don't have any pending PRs. Can you assign me this one.

okay
