### ISSUE TITLE
WIFI password viewers

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#239]
## Script Title - Able to see passwords of connected wifis

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Ajay-Raj-S** [comment]
Hello @pawangeek, I would like to work on this, can you assign this to me? please.

**Comment by pawangeek** [comment]
okay, fine
