### ISSUE TITLE
SMS location

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#240]
## Script Title - Sms your current location.  An updated version of #65 

**what will change** - Adding a script 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by bunnysworld** [comment]
hey @pawangeek  can you assign me with this issue

**Comment by pawangeek** [comment]
Sure @bunnysworld :)

**Comment by bunnysworld** [comment]
hey @pawangeek  i had made a PR of my work will you give your review over it
