### ISSUE TITLE
ZIP password cracker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#241]
## Script Title - Add script to crack password of password-protected zip

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by fa1l** [comment]
Hi! I can do this

**Comment by pawangeek** [comment]
sure

**Comment by kanekiken9** [comment]
Hey Pawan!
I guess that I need to create a dictionary of passwords and then add a code which selects the right one in that dictionary.
Is it what we need to do ?

**Comment by fa1l** [comment]
I'm already doing this issue and will make a PR in couple of hours :)
