### ISSUE TITLE
Autoclicker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#25]
## Script Title - We can use that for auto-clicking

**what will change** -  Adding auto clicker

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Sacrezar** [comment]
Hi, can you assign this to me?

**Comment by pawangeek** [comment]
Sure, go ahead :)
