### ISSUE TITLE
corona-gif-mapping

### ISSUE THREAD

**Issue by bunnysworld** [python-geeks/Automation-scripts#251]
## Script Title -Add corona maping gif

**what will change** -Adding script that fetch data and map it according to corona cases

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by bunnysworld** [comment]
hey @pawangeek can you assign me with this 
here is the amount of work i alredy did  :-   https://github.com/bunnysworld/c-19-gif

**Comment by pawangeek** [comment]
That's cool @bunnysworld but currently, we're focusing mainly on automation tools, this is more like the data analysis part. Hope you understand

still you can submit this to [awesomeScripts](https://github.com/Py-Contributors/awesomeScripts) By Py-contributors and [code-n-stitch](https://github.com/bislara/code-n-stitch) By Bislara.

**Comment by bunnysworld** [comment]
thanks for suggestion @pawangeek
