### ISSUE TITLE
Weather checker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#26]
## Script Title -  Able to check weather by any related API

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by niccolomarcon** [comment]
Can i take this?

**Comment by pawangeek** [comment]
Sure go ahead :)
