### ISSUE TITLE
Google meet Joiner

### ISSUE THREAD

**Issue by m4dummies** [python-geeks/Automation-scripts#278]
## Online class automator

**This script will let you join the class easily. All you need to do is exec the program or schedule it.** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by happyeric77** [comment]
@m4dummies 
Does it mean the script need to access specific online course (by API?) such as Udemy or Coursera?

**Comment by pawangeek** [comment]
Hey @m4dummies can you brief more about it like google meet, zoom, skype, Microsoft teams, or any other?

**Comment by m4dummies** [comment]
> @m4dummies
> Does it mean the script need to access specific online course (by API?) such as Udemy or Coursera?

No i simply mean that i provide the program with the link to my class and it automatically joins it.

**Comment by m4dummies** [comment]
> Hey @m4dummies can you brief more about it like google meet, zoom, skype, Microsoft teams, or any other?

Google meet

**Comment by m4dummies** [comment]
Can i myself try this @pawangeek ?

**Comment by pawangeek** [comment]
> > Hey @m4dummies can you brief more about it like google meet, zoom, skype, Microsoft teams, or any other?
> 
> Google meet

so you're gonna use selenium or something?  to automate that

**Comment by pawangeek** [comment]
> Can i myself try this @pawangeek ?

You should make a PR for the first assigned issue first

**Comment by m4dummies** [comment]
Hi @pawangeek can you assign this to me?

**Comment by Muskan33** [comment]
hey, can you please assign this issue to me? I have experience with selenium.

**Comment by pawangeek** [comment]
okay @Muskan33 try to come up with solution

**Comment by m4dummies** [comment]
can u assign this to me?

**Comment by m4dummies** [comment]
hi @pawangeek  i submitted a pr, but it got declined. Could u help me with what the problem was?

**Comment by pawangeek** [comment]
Just remove the linting errors @m4dummies . flake8 here

**Comment by m4dummies** [comment]
Hi @pawangeek i completed this issue.
