### ISSUE TITLE
Remove audio from video

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#279]
## Script Title - Audiofrom_videoremover

**Brief** - Script should able to remove all audio from any video

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by happyeric77** [comment]
@pawangeek Might I work on this script?

**Comment by pawangeek** [comment]
Sure @happyeric77
