### ISSUE TITLE
Wallpaper changer

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#28]
## Script Title - Able to change my desktop wallpaper

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Sacrezar** [comment]
Willing to do it, but what do you want exactly ? A script with an hardcoded path to your images that choose a random pic in there when launched?

**Comment by pawangeek** [comment]
Yes it should be random, you can use something like random lib to generate that value and the path should be hardcoded
