### ISSUE TITLE
Adding text in Videos at top

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#280]
## Script Title - Video_textadder

**Brief** - Script should able to add text at the top of the video (User have the choice to customize font size)

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by happyeric77** [comment]
@pawangeek 
I am also able on this task. Could you assign it to me?

**Comment by pawangeek** [comment]
The first task first. I will surely assign this to you :)

**Comment by happyeric77** [comment]
@pawangeek 
The first one have been merged. Might I start working on this task?

**Comment by pawangeek** [comment]
Yes, you can
