### ISSUE TITLE
Programming Quoter

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#281]
## Script Title - programming_quoter

**Brief** - It should display a programming quote as toast notifs on running (should use win10toast lib for that)

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by ShubhamNagure** [comment]
Hi @pawangeek 
Please assign me.

**Comment by pawangeek** [comment]
Sure @ShubhamNagure

**Comment by ShubhamNagure** [comment]
Hi, @pawangeek,
Done, Please check #294 PR. 
Thanks for giving me this opportunity.
