### ISSUE TITLE
CF solution Submit

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#282]
## Script Title - cfsol_submitter

**Brief** - Script should able to submit code forces solution on behalf of user

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Divyansh-20** [comment]
@pawangeek 
I'd like to contribute to this, could this be assigned to me?

**Comment by pawangeek** [comment]
Sure @Divyansh-20 , go ahead
