### ISSUE TITLE
QR code scanner

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#29]
## Script Title - Able to scan QR code

**what will change** - Adding script of QR code

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by rkgeekoftheweek** [comment]
@pawangeek , Please assign this to me.

**Comment by pawangeek** [comment]
Sure go ahead :)
