### ISSUE TITLE
Non Blocking Audio for Recorder Raspberry PI

### ISSUE THREAD

**Issue by JenishRudani** [python-geeks/Automation-scripts#291]
## Script Title - non_blocking_audio_recorder.py

**Brief** - This audio recorder scripts would allow users to record wave files like a handheld record would allow but fo raspberry pi. 

Press the button -> Start Recording
Hold the button -> Recording State
Release the Button -> Stop Recording and save the file to the appropriate location with name and a timestamp

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by JenishRudani** [comment]
@pawangeek Could I work on this script?

**Comment by pawangeek** [comment]
Okay @JenishRudani go ahead, concept looks good
