### ISSUE TITLE
Youtube Subscriber

### ISSUE THREAD

**Issue by Sacrezar** [python-geeks/Automation-scripts#298]
**Describe the bug**
You need to log before trying to subscribe to a channel 

**To Reproduce**
Just launch the script `youtube.py` in folder `youtube_subdownloader`

**Expected behavior**
The script must handle when the user isn't connected. Either it asks the user or we hardcode it.

**Screenshots**
![image](https://user-images.githubusercontent.com/38185428/96416200-fd551680-11ef-11eb-8c96-55e58c1c2b4b.png)

**Additional context**
Other details:
* The name `youtube_subdownloader` is misleading, `youtube_subscriber` would have been better imo.
* `open = webdriver.Chrome()` will not work if you don't have Chrome in your PATH.
![image](https://user-images.githubusercontent.com/38185428/96416110-de568480-11ef-11eb-943b-0739d694cf6b.png)
Maybe, something like this 👇 would work or we make it like it must handle multiple browsers.
```python 
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())
```

**Comment by Sacrezar** [comment]
I must admit, I find the usefulness of this script rather limited (even if we make it work). 
Maybe we should just delete it? Don't know

**Comment by pawangeek** [comment]
Yes, @Sacrezar that's not a useful script. Just adding a subscriber to any channel with no error-handling/error-flashes. 
It's good we should remove it. Just make a PR deleting it
