### ISSUE TITLE
Detect language and translator

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#30]
## Script Title - We can use google trans or similar library for achieving results

**what will change** - Adding script for language detector and translator

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by janethavi** [comment]
Hi, can you please assign this issue for me?

**Comment by pawangeek** [comment]
Sure, go ahead
