### ISSUE TITLE
Mp3 music player

### ISSUE THREAD

**Issue by sanju6890** [python-geeks/Automation-scripts#306]
## Script Title - Mp3 music player

**Brief** - A mp3 player with a pleasing GUI. An application developed using python-tkinter. The application will be having the functionality of play, pause, next, previous, add single song, and add multiple songs.

## Programming Language

- [x] Python

Kindly review my issue and confirm if I can contribute or not.

**Comment by pawangeek** [comment]
Hey @sanju6890 we already have the same script named as a music player #147. If you want to work on something like this we have another open issue #199 (Just a little advance version of this) :)

**Comment by sanju6890** [comment]
Ok, Thanks for letting me know :)

**Comment by pawangeek** [comment]
Comment on #199 if you want to work. Thanks :)
