### ISSUE TITLE
Broken link Finder

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#307]
## Script Title - broken_linkfinder

**Brief** - A script that detects broken links in a website provided by the user (one can use requests, soupsieve or similar libs)

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by harshitashankar** [comment]
Please assign this to me.

**Comment by pawangeek** [comment]
Okay fine @harshitashankar

**Comment by harshitashankar** [comment]
Hey @pawangeek , Do you want the script to recursively check for broken links too? e.g. if xyz.com contains some link abc.com which is not broken, should search be done for abc.com as well?

**Comment by pawangeek** [comment]
@harshitashankar It's really good if you come up with a solution for multiple redirects.
