### ISSUE TITLE
Bulk mail sender

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#308]
## Script Title - bulkmail_sender

**Brief** - Script which sends an email to all mail-address from files like csv, xlsx, etc.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by m4dummies** [comment]
Please assign this to me.
@pawangeek

**Comment by pawangeek** [comment]
Cool @m4dummies

**Comment by m4dummies** [comment]
Hi @pawangeek , should i close this issue. I submitted the PR.
