### ISSUE TITLE
Email validator

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#31]
## Script Title - Simply do it by regex library

**what will change** - Adding email validator

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by javmarina** [comment]
Can you assign it to me?

**Comment by pawangeek** [comment]
Sure, go ahead

**Comment by javmarina** [comment]
Can be closed. Thanks!
