### ISSUE TITLE
Google Image scraper

### ISSUE THREAD

**Issue by Sripaad** [python-geeks/Automation-scripts#312]
## Script Title -
Google image scraper
**Brief** -
Script that takes in search keyword and scrapes images from google images.
## Instructions
- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Sripaad** [comment]
@pawangeek youve been mentioned a lot in the issues so am asking you, can i finish this up?

**Comment by pawangeek** [comment]
@Sripaad good idea for a new script and go ahead, but I have some doubts regarding the script like

(i) Is there any args for getting images for it just scrapes the first one?
(ii) Are we going to scrape from thumbnails like a small photo or full image size?

**Comment by Sripaad** [comment]
@pawangeek Yes, there will be cli for search keyword, number of images(approx) and save dir. It will scrape full size images, just like google image searching for something and downloading a bunch of it.
