### ISSUE TITLE
An edit to CONTRIBUTION.md is needed?

### ISSUE THREAD

**Issue by funbeedev** [python-geeks/Automation-scripts#315]
I just wanted to report that when I followed the instructions in the [CONTRIBUTION.md](https://github.com/python-geeks/Automation-scripts/blob/main/CONTRIBUTING.md) this step failed:
```
git pull upstream master
```

I had to run this instead:
```
git pull upstream main
```
Just FYI in case this is something that needs updating.

**Comment by pawangeek** [comment]
Thanks for that @funbeedev
