### ISSUE TITLE
Application Starter

### ISSUE THREAD

**Issue by m4dummies** [python-geeks/Automation-scripts#318]
##Application launcher -

**The script will automatically run the application specified on computer startup.** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by m4dummies** [comment]
@pawangeek  If possible i you could assign this too me. Its a interesting automation project.

**Comment by sandeep3136** [comment]
assign me and explain a bit

**Comment by m4dummies** [comment]
> assign me and explain a bit

Alright, So basically the script should run at startup. The script will then run any 2 applications, and will open the browser of choice with any website(example netflix).

**Comment by pawangeek** [comment]
what kind of applications @m4dummies

**Comment by m4dummies** [comment]
> what kind of applications @m4dummies

So what i mean is that, once your computer starts all your most used or favourite applications should launch. For instance, discord and word can run. Also a web browser with lets say your favourite song playlist on youtube.

**Comment by pawangeek** [comment]
TBH not much useful. We have diff moods and work on every single day

**Comment by pawangeek** [comment]
Still, if you wanna work I can assign it to you

**Comment by m4dummies** [comment]
@pawangeek  
can u assign it to me?

**Comment by m4dummies** [comment]
@pawangeek  thank you

**Comment by m4dummies** [comment]
Hi @pawangeek , I did a little research and as you said it doesn't make any sense making a script that starts applications. Instead can i make a script that opens the browser with any url or your favourite song playlist?
