### ISSUE TITLE
Check Github username

### ISSUE THREAD

**Issue by pinho** [python-geeks/Automation-scripts#328]
## Script Title - Check Github username

Check if a Github username is being used.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pinho** [comment]
Assign to me, please.

**Comment by pawangeek** [comment]
@pinho good idea for a new script but TBH it's not much useful as an "automation script".  Like one can easily check if a name is available or not and one rarely use a script for that. Hope you understand :)

You can submit them in similar repos like [Code-n-stich](https://github.com/bislara/code-n-stitch) By Bislara or [Awesome-scipts](https://github.com/Py-Contributors/awesomeScripts) by Py-contributors

**Comment by arnav-deep** [comment]
@pawangeek 
I have a script that can do this. Assign it to me and I will send a PR.
