### ISSUE TITLE
Zipfile extractor

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#33]
## Script Title -  Task is to create a zip file extractor in using Python 
(Simply able to achieve that by "zipfile" pypi package

**what will change** - Adding script of zipfile extractor

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Tazminia** [comment]
Hello, willing to work on this if possible

**Comment by pawangeek** [comment]
Sure go ahead :)

**Comment by jayaganeshkumar** [comment]
@pawangeek  I have completed the code required for this. Can you assign it to me?

**Comment by jayaganeshkumar** [comment]
> @pawangeek I have completed the code required for this. Can you assign it to me?

@pawangeek 

Can I work on this?

**Comment by pawangeek** [comment]
okay sure
