### ISSUE TITLE
Discount Alter improvement !!

### ISSUE THREAD

**Issue by ashkankamyab** [python-geeks/Automation-scripts#330]
## Feature: Add tor proxy to discount_alerter

It could possibly be an IP tracker or WAF on the edge of the target. I want to add a **tor proxy** to this. I made some prototype already and sure how to implement it. 

## Feature: Handle more than one Item in row

The main function of script accepts only one arg at the moment. I assume we can implement multi arg using built-in `**args` feature. 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by ashkankamyab** [comment]
shouldn't we have feature request template :1st_place_medal:
:grinning:

**Comment by pawangeek** [comment]
> It could possibly be an IP tracker or WAF on the edge of the target.

@ashkankamyab can you bit elaborate on this, I still don't get the idea :(

**Comment by ashkankamyab** [comment]
> > It could possibly be an IP tracker or WAF on the edge of the target.
> 
> @ashkankamyab can you bit elaborate on this, I still don't get the idea :(
> 
> 

Sure,
Well, the goal I want to achieve is to get notification not just for one item but let's say a list of items. Currently the script sends a request every 12 Hour. But what if it sends 10 request? Or more?
So my idea is to imolement a tor proxy in between, with which the requests will be sent through a new gatway hub (simply with a new ip). 
If you do agree to implement this the second point(alerter for more item in row) could be applied as well...

Let me know your opinion.
BR

**Comment by ashkankamyab** [comment]
I'll close this. this is a bit controversial as I realized
