### ISSUE TITLE
Add a board generator function to the solve_sudoku script

### ISSUE THREAD

**Issue by DMeurer** [python-geeks/Automation-scripts#335]
## Sudoku Board generator

**Brief** -
Add a function to genearte sudoku boards. 

Im too lazy to type in all the numbers of the board therefore i think a function to generate boards wold be nice

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Im sorry i made a pr before i was assigned my issue.

It would be nice if you can assign me or review my pr anyways.

**Comment by MadhuMadhavanSridhar** [comment]
Hello,
Can I work on this issue?

**Comment by pawangeek** [comment]
Duplicate of #6
