### ISSUE TITLE
Video Cropper

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#338]
## Script Title - 

**Brief** - Script to crop video 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Crozzers** [comment]
I'm willing to take a crack at this

**Comment by pawangeek** [comment]
cool go ahead :)
