### ISSUE TITLE
Video color to black and white

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#339]
## Script Title -

**Brief** - Script able to change the color of video

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Crozzers** [comment]
I wouldn't mind doing this one

**Comment by pawangeek** [comment]
Perfect go ahead :)
