### ISSUE TITLE
Bulk Rename

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#34]
## Script Title - Script should able to change the name of files in bulk

**what will change** - Adding bulk renamer

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Sacrezar** [comment]
Can I do this one? Is it just a bulk renamer for all files in a folder?

**Comment by pawangeek** [comment]
Yes exactly, Just rename them like 1,2,3.... or a,b,c or any other pattern you want. Okay I am assigning this to you
