### ISSUE TITLE
Directory Organizer

### ISSUE THREAD

**Issue by akashydv7** [python-geeks/Automation-scripts#345]
## Script Title - dir_organizer
**Brief** - simple script to organize directory by putting different types files in respective folders based on extensions 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by akashydv7** [comment]
Can I work on this ?

**Comment by pawangeek** [comment]
Hey @akashydv7, I think the issue is the same as merged by #220 isn't it?

**Comment by akashydv7** [comment]
I guess it's the same. Sorry I should have looked for that.
