### ISSUE TITLE
Todo App

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#35]
## Script Title - Panda should able to keep a record of lazy todo works :) 
You can create that if you know flask/Django or by GUI like Tkinter

**what will change** - Adding todo app

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by aayuv17** [comment]
Hey, can you please assign this issue to me?

**Comment by pawangeek** [comment]
Sure :)
