### ISSUE TITLE
Spammer

### ISSUE THREAD

**Issue by stifler6005** [python-geeks/Automation-scripts#350]
## Script Title -spam.py

**Brief** -
It is a gui software that ask for a spam message and number of messages after that it gives you 10 seconds to put your cursor at the text box of the messaging app.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by sourabh112** [comment]
hey, can I have this issue?
I'm quite new to this so I might need some guidance. I think the task is fairly simple to implement using pynput But I don't quite understand the GUI part. If you can explain a bit more about that.

**Comment by pawangeek** [comment]
Hey @stifler6005 need more clarity for the script

**Comment by sourabh112** [comment]
I looked into this and I have some questions about it. And after that, I think I can start working on it.
1) What Type of GUI should be made for this project/issue ? Is it on assignee or are there any standards to follow ?
2) Should it be a python script like other projects or assignee have to add a .exe file also?
3) What kind of message platforms it is intended for? I mean as to send messages ENTER keyword should be used by default?
If the above-mentioned questions are already answered/discussed somewhere else then excuse my ignorance. As it is my first open-source contribution.

**Comment by pawangeek** [comment]
Hey @sourabh112 you can check the other issues, until the objective is cleared by author

**Comment by stifler6005** [comment]
Done.
