### ISSUE TITLE
Backup a file/folder into a zip file

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#351]
## Script Title - 

**Brief** - Copies the whole contents of any folder into a zip file

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pranxv** [comment]
I am interested ! Can I take up this task?

**Comment by pawangeek** [comment]
Sure, go ahead

**Comment by vishaljha2121** [comment]
Hello, I want to contribute to this issue. Can someone please guide me? It is my first time working with open source project contributions. 

Thanks,
Vishal
