### ISSUE TITLE
Facebook Video Downloader

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#352]
## Script Title -

**Brief** - Script should able to download FB video by url

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by samkap333** [comment]
I'm interested. Can I have this issue?

**Comment by pawangeek** [comment]
Sure @samkap333

**Comment by CodeBunny09** [comment]
oh! sorry i didn't see it earlier, that it was meant for those who are assigned to.....

**Comment by CodeBunny09** [comment]
how do I cancel my pull request?

**Comment by cyberbaaz** [comment]
Can i work on this issue?
