### ISSUE TITLE
PDF to Audio

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#353]
## Script Title -

**Brief** - Script to convert PDF to a audio

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by sourabh112** [comment]
I am interested in this. Can I have this issue?

**Comment by pawangeek** [comment]
Go ahead

**Comment by Shahzeb-A** [comment]
Hello, @pawangeek I'm interested, is this issue still available? or any other

**Comment by sourabh112** [comment]
@pawangeek I have completed this and made a pull request. Can you please review it? and guide me if I need to do something else.

**Comment by pawangeek** [comment]
@sourabh112 solve the linting issues
