### ISSUE TITLE
PDF to word/doc

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#354]
## Script Title -

**Brief** - Script for convert .pdf file back again to .doc

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by atharvanaik225** [comment]
@pawangeek can I have this issue?

**Comment by sandipan898** [comment]
Hey @pawangeek , can I take a part to solve this issue?
