### ISSUE TITLE
Auto_Calender

### ISSUE THREAD

**Issue by candc-admin** [python-geeks/Automation-scripts#357]
## Add AutoCalender -

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
**noted

### Programming Language

- [x] Python

I wanna be part of this Happy Coding Communiy?
May i?

**Comment by pawangeek** [comment]
Go ahead @candc-admin

**Comment by candc-admin** [comment]
Thank you!!
