### ISSUE TITLE
Captcha Solver

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#36]
## Script Title - Should able to solve the captcha. can be done by library like "pytesseract" for that

**what will change** - Adding captcha solver

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by gkydev** [comment]
Hi can you assign this to me

**Comment by pawangeek** [comment]
Yeah sure :)
