### ISSUE TITLE
Corona Information Tracker and Visualizer 

### ISSUE THREAD

**Issue by sandipan898** [python-geeks/Automation-scripts#362]
## Corona Information Tracker and Visualizer #362

**Brief** - 
Corona Information Tracker and Visualizer using graphs and tabular data through a graphical interface.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language
- [x] Python

### Technologies Involved
- [x] Data Visualization
- [x] Data Fetching and API Integration
- [x] GUI Development

May I solve this as an issue and work on it to add this new feature?
Happy Coding!

**Comment by sayantann11** [comment]
can i take this issue i am new to this but as a task i really need guidance and wanted to contribute for the same anyone if can help me and show a way to fix the issue will really help

**Comment by sayantann11** [comment]
@pawangeek please guide me

**Comment by sandipan898** [comment]
@pawangeek can you please open this issue and assign myself to work on it?
I will make the pull request within 1 or 2 days.

**Comment by pawangeek** [comment]
Ohk, but please do that this time
