### ISSUE TITLE
Automated Voice based Prescription Generator

### ISSUE THREAD

**Issue by sandipan898** [python-geeks/Automation-scripts#364]
## Automated Voice based Prescription Generator

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

May I solve this as an issue and work on it to add this new feature? 
Then please consider assigning it to myself so that I can be a part of this community.
Happy Coding!

**Comment by Adyyousf** [comment]
Can i work on it?

**Comment by Adyyousf** [comment]
Hey @sandipan898  can I work on it?

**Comment by sandipan898** [comment]
Hey @Adyyousf  I'm willing to assign it to myself, so if I need any help I'll create another issue where you can work on.
