### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#37]
## Script Title - Music Player ( Can be done by library like pygame or similar)

**what will change** -  Adding simple music player

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by gkydev** [comment]
Hi can you assign this to me

**Comment by pawangeek** [comment]
Hey, can you please make a PR to your previous issue?
