### ISSUE TITLE
Browser Notification Sender

### ISSUE THREAD

**Issue by razorblade42** [python-geeks/Automation-scripts#374]
## Script Title -Browser Notification Sender

**Brief** - This application sends browser notifications to other devices from your device.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Can i be assigned for this ?
Happy Coding

**Comment by pawangeek** [comment]
Sure, go ahead, So is it like something cross platform notifier, need some more details beforehand

**Comment by razorblade42** [comment]
Yeah so , what i meant to say is the user will be able to send any type of notification to linked devices using a python program.

**Comment by pawangeek** [comment]
Ohh that's great, yeah sure go ahead

**Comment by razorblade42** [comment]
Hi , @pawangeek I have made a PR you can have a look and let me know if there is any problem.

Thanks!

**Comment by pawangeek** [comment]
> Hi , @pawangeek I have made a PR you can have a look and let me know if there is any problem.
> 
> Thanks!

Check and resolve linting errors

**Comment by razorblade42** [comment]
> > Hi , @pawangeek I have made a PR you can have a look and let me know if there is any problem.
> > Thanks!
> 
> Check and resolve linting errors

I think i solved that linting error, can you have a look?
