### ISSUE TITLE
python-music-downloader

### ISSUE THREAD

**Issue by siddharth1704** [python-geeks/Automation-scripts#375]
## Script Title -Music downloader

**Brief** -
This is a script that will help to download music in mp4 format from youtube i am also thinking to add a player as well
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding
Can you please assign me on this project

**Comment by pawangeek** [comment]
Sure, go ahead but make sure, it will download just audio, we already have youtube video downloader #159

**Comment by siddharth1704** [comment]
ok thanks alot

**Comment by siddharth1704** [comment]
@pawangeek  i have generated the PR kindly look into it

**Comment by siddharth1704** [comment]
#393 I have generated this PR kindly check into it
