### ISSUE TITLE
IP-Tracker

### ISSUE THREAD

**Issue by siddharth1704** [python-geeks/Automation-scripts#376]
## Script Title -IP_tracker

**Brief** -
This script will help in tracking down an ip adress using an external api 
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding
Can you please assign me this project

**Comment by kuspia** [comment]
Can i work on this please assign me.

**Comment by nk636547** [comment]
Can I work on this.
please assign me

**Comment by Architrixs** [comment]
May I work on this...

**Comment by pawangeek** [comment]
Sure @Architrixs

**Comment by jayaganeshkumar** [comment]
Hey can I work on this?
