### ISSUE TITLE
Spell Corrector

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#38]
## Script Title - Should able to correct spelling ( Can be done by textblob library)

**what will change** - Adding spell corrector module

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by SaiSrichandra** [comment]
I would like to do this

**Comment by pawangeek** [comment]
okay, go-ahead

**Comment by jaypaliwal1212** [comment]
Is this issue still available? If yes, can I work on it?

**Comment by pawangeek** [comment]
okay sure, go ahead :)
