### ISSUE TITLE
Employee attendance automator

### ISSUE THREAD

**Issue by sayantann11** [python-geeks/Automation-scripts#380]
## Script Title -

**Brief** -
automatic employee attendance system using Facial Recognition helps banks and industries to take attendance with out any biometrics and human interference which reduces the chance of transferring COVID'19 through any human interference.
 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python
May I solve this as an issue and work on it to add this new feature?
Happy Coding

**Comment by danger-ahead** [comment]
Can I help?
Would need more details on this issue

**Comment by sayantann11** [comment]
sure if pawan allows us to do i will need help

**Comment by sayantann11** [comment]
i already made some script you can see ,find and remove bugs @danger-ahead

**Comment by pawangeek** [comment]
Hey @sayantann11 it looks like a complete project, rather than a script 😄😄, Anyway if wanna add it here, feel free to do.

**Comment by sayantann11** [comment]
thanks pawangeek but its just a script for now. :D 
many more work is needed to complete it as a project

**Comment by sayantann11** [comment]
I have perform these changes 
https://github.com/python-geeks/Automation-scripts/pull/390
you can refer this pull request i request you to accept this.

**Comment by Bhanudeep** [comment]
@pawangeek I have an entire project dedicated to marking Attendance of our faculty. It is a complete end to end project. I would be happy to merge it here. Please check my Deep-learning for this. I have multiple versions of this project as well. It primarily involves Raspberry pi for capturing , sending image to server. receiving acknowledgment form server, Standalone Raspberry pi module which handles Everything on the device itself.
I would love to put it here. it is almost bug free, and more Importantly it has SPOOF DETECTION . 
Please Assign me to this.
