### ISSUE TITLE
Recommendation_system

### ISSUE THREAD

**Issue by siddharth1704** [python-geeks/Automation-scripts#388]
## Script Title -
This will be recomendation system of amazon i know it is a whole project moreover it is a  small script afte a whole lot of research
**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding
Can you please assign me on this

**Comment by pawangeek** [comment]
Nope this can't need be automated, make some simple utilities, for solving day to day repeated tasks
