### ISSUE TITLE
Semantic Segmentation Implementation-U-Net

### ISSUE THREAD

**Issue by msethi006** [python-geeks/Automation-scripts#389]
## U-Net Implementation

**Brief** - This will help users to train, predict, deploy Semantic Segmentation model ( U-Net) on their own datasets.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python
May I solve this as an issue and work on it to add this new feature?
Happy Coding

**Comment by pawangeek** [comment]
Hey @msethi006, this don't need to be automated, we are try to automating our day to day or very basic tasks (like utilities type, eg. stopwatch, timer, alarm, etc.). Hope you understand :)
