### ISSUE TITLE
Drawing bounding boxes with the color same as the detected object.

### ISSUE THREAD

**Issue by shreyasvedpathak** [python-geeks/Automation-scripts#391]
## Script Title - Draw bounding boxes with the colour same as the detected object.

**Brief** -
Essentially, the colour of a detected object may be used to determine the bounding box colour. At first glance, this may not appear to be very beneficial, but there are instances where it may be useful, such as in security checkouts, regular screening, and so on. This is a utility function that I am currently developing and believe will benefit others. Since this is not an Object Detection project, but rather a post-training utility function, I believe it needs to be included here. 

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python
- [x] OpenCV or PILLOW

Happy Coding

**Comment by shreyasvedpathak** [comment]
@pawangeek can you assign me?

**Comment by pawangeek** [comment]
@shreyasvedpathak , this repo is specifically to automate our day to day task, Make a automated use of this, turning up/down volumn, sstud down/on laptop, etc. If you wanna make something with Opencv. Like who wants to draw bounding box, for our day to day tasks, Hope you understand :)

**Comment by shreyasvedpathak** [comment]
@pawangeek got it. thanks.
