### ISSUE TITLE
URL Shortened

### ISSUE THREAD

**Issue by anshul2807** [python-geeks/Automation-scripts#394]
## Script Title - URL Shortened

**Brief** -
Url shortened will convert any length Url into 4 character URL. 

FOR  example -- 
Url --> www.geeksforgeeks.com/problems
After Conversion -- 
Url --> www.myUrl/DIKH

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by anshul2807** [comment]
Pls Assign the issue to Me.

**Comment by pawangeek** [comment]
@anshul2807, we already have same in #40
