### ISSUE TITLE
Chrome Dino Bot

### ISSUE THREAD

**Issue by anshul2807** [python-geeks/Automation-scripts#395]
## Script Title - Chrome Dino Bot

**Brief** -
I would like automate the Chrome Dino Game. 
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by anshul2807** [comment]
Pls assign this issue to me.

**Comment by pawangeek** [comment]
@anshul2807 This is not a automated action to solve any day to day task
