### ISSUE TITLE
Price Tracker

### ISSUE THREAD

**Issue by chauhanarpit09** [python-geeks/Automation-scripts#397]
## Script Title -

A Price Tracker will help you to track the price for all your favorite products and whenever the price drops down it will automatically send you an email

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by chauhanarpit09** [comment]
Please, assign this issue to me.

**Comment by pawangeek** [comment]
Go ahead @chauhanarpit09

**Comment by anshul2807** [comment]
> Go ahead @chauhanarpit09

Can you Assign me any task??
really urgent...
