### ISSUE TITLE
Jarvis(assistant)

### ISSUE THREAD

**Issue by anshul2807** [python-geeks/Automation-scripts#398]
## Script Title - Jarvis(assistant) .

**Brief** -
Our virtual assistant will able to do the followings things-

Weather forecasting, Launch Games, Launch Windows Applications, Open Websites, tells you about almost everything you ask, tells you date and time, greetings, news, etc.

You can interact with your laptop’s microphone/console. The response generated by the assistant will display on the console or as a speech via the speaker

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pawangeek** [comment]
Seems pretty good idea, go ahead

**Comment by anshul2807** [comment]
Done with the task.
