### ISSUE TITLE
Add screenshot taker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#4]
## Script Title - Screenshoter

**what will change** - It able to take screenshot just by two clicks of mouse

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by GaganSingh5** [comment]
Hi dev, i want to work on this

**Comment by pawangeek** [comment]
Sure, It's like we can click on two points over the screen and it will capture a screenshot of that. For reference, you can see go though [link](https://github.com/python-geeks/Automation-scripts/blob/main/autotyper/autotyper.py). Further just try and come up with an initial solution we will try to complete it :)
