### ISSUE TITLE
Image steganography 

### ISSUE THREAD

**Issue by Sandhya1708** [python-geeks/Automation-scripts#401]
## Script Title - Image Steganography

**Brief** - When we give an image and a message as an input , the message given would be encrypted twice ,i.e., the message is encrypted and a cypher text is obtained. The cypher text is then encrypted into the edge of the image. 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by jonyeru23** [comment]
Hi this is my first time contributing, i would love to give it a shot!

**Comment by jonyeru23** [comment]
Is the image a path to the image file?

**Comment by Sandhya1708** [comment]
Well, the code I wrote takes the image as input.

**Comment by Sandhya1708** [comment]
I have not yet added the code into this page. I wanted to contribute , so I had put up this issue .

**Comment by jonyeru23** [comment]
def encrypt_and_hide(text, image):
    public_key, private_key = rsa.newkeys(512)

    encMessage = rsa.encrypt(text.encode(), public_key)

    with open(image, 'ab') as f:
        f.write(encMessage)

well this is the little function i wrote for your problem, tell me if it works for you
