### ISSUE TITLE
Instagram Scraper 

### ISSUE THREAD

**Issue by AashutoshNirwal** [python-geeks/Automation-scripts#403]
## Script Title -Instagram  Scraper 

**Brief** - Python automation script to search for posts on an Instagram page and download them. 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by AashutoshNirwal** [comment]
please assign it to me

**Comment by kaushikaryan04** [comment]
@AashutoshNirwal Hey can i help in any way?

**Comment by sannamir** [comment]
Is this issue still open?

**Comment by pawangeek** [comment]
Yup @sannamir it is, you can work on it
