### ISSUE TITLE
Certificate Generator issue

### ISSUE THREAD

**Issue by kuspia** [python-geeks/Automation-scripts#419]
./certificate_generator/app/__init__.py:6:23: E261 at least two spaces before inline comment, 

while my ml_solver script is getting built I am getting this issue so kindly fix the linting issue asap.

**Comment by chauhanarpit09** [comment]
@pawangeek can you assign this task to me

**Comment by pawangeek** [comment]
Hey I won't see any bug in downstream @kuspia, can you please recheck

**Comment by kuspia** [comment]
Ok cool #416 was my PR and it has passes all test earlies idk why but as desribed above i was getting that issue

I will close it.
