### ISSUE TITLE
Currency Convertor

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#43]
## Script Title - Script is able to convert currencies

**what will change** - Adding currency convertor script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by maheshschand** [comment]
Hello, Can you please assign this issue to me?

**Comment by jayaganeshkumar** [comment]
@pawangeek  I have this code ready. Can you assign me this?

**Comment by pawangeek** [comment]
Okay, I will assign this to @maheshschand.
