### ISSUE TITLE
Password strength  checker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#44]
## Script Title - Able to detect one' password is strong or not

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by falguni-k** [comment]
Hey I  would like to work on this issue. Can you clarify what characteristics you would consider in a strong password? Or should I set them myself?

**Comment by pawangeek** [comment]
Sure go ahead, and it should be consist of lowercase, uppercase, special character, digit and have >= 8 chars is sufficient

**Comment by jaypaliwal1212** [comment]
Is this issue still available? If yes, can I work on it?

**Comment by pawangeek** [comment]
hey @jaypaliwal1212. Linked PR is in review can you check other issues
