### ISSUE TITLE
alarm_clock : Add snooze feature 

### ISSUE THREAD

**Issue by Supaku9** [python-geeks/Automation-scripts#440]
**Brief:** Add the feature of snooze option to the alarm clock

**Instructions:**

> Include snooze option in the alarm clock

> Provide the option of alarm label

**Programming languages:**
Python

**Comment by Supaku9** [comment]
@pawangeek can I get assigned to this issue

**Comment by Supaku9** [comment]
Thank you @pawangeek

**Comment by sannamir** [comment]
Hey! I am new at open source contribution. Can I work on this issue?
