### ISSUE TITLE
Youtube_to_mp3

### ISSUE THREAD

**Issue by MMM-9** [python-geeks/Automation-scripts#443]
## Script Title - Automatic YouTube to mp3 converter

**Brief**  -  For someone who would love to hear famous dialogue's in movies or would love to hear their favorite musical notes found only on YouTube !  It downloads the video and further converts it to mp3 format automatically. All one has to do is only paste the video link!

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by MMM-9** [comment]
I would like to work on this issue. Please assign me this.

**Comment by MMM-9** [comment]
@pawangeek Can I get assigned to this issue?

**Comment by pawangeek** [comment]
Hey @MMM-9 we have a similar script here #159

**Comment by MMM-9** [comment]
Hi @pawangeek , the script here is also converting it to MP3 after download, so its level up from #159, specially used for people who want songs/speech or as audio books as mp3 in their systems.

**Comment by pawangeek** [comment]
Cool than for it, but make sure, it don't have option for downloading videos, always download a audio format

**Comment by MMM-9** [comment]
@pawangeek how can I add my code in this repo as when I followed the steps, a permission denied error was coming.
![image](https://user-images.githubusercontent.com/63444165/131380767-57036e10-8817-4a4b-bb84-f692cabdd3cf.png)

**Comment by MMM-9** [comment]
@pawangeek I tried to resolve the flake8 error, so should I just edit my script in the pull request #451 or should I create a new pull request?
