### ISSUE TITLE
Automating the HR interview process

### ISSUE THREAD

**Issue by paridhi2105** [python-geeks/Automation-scripts#444]
## Script Title - Automating the HR interview process

**Brief** - I want to add a bot for automating the HR interview process. It will ask some relevant questions from the candidate and assign a score out of 10. The score will determine whether the person has passed the HR interview and be considered as a good fit for the company.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by paridhi2105** [comment]
Can I be assigned to this issue?

**Comment by pawangeek** [comment]
Sure go ahead @paridhi2105
