### ISSUE TITLE
Script Title - Automatic Hate speech detector 

### ISSUE THREAD

**Issue by abhishekchopra0907** [python-geeks/Automation-scripts#445]
## Script Title -Automatic Hate speech detector

**Brief** -Create a script for detecting if a given text contains hate speech or not 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by abhishekchopra0907** [comment]
@pawangeek can you please assign this issue to me

**Comment by pawangeek** [comment]
We don't need a automation for that
