### ISSUE TITLE
Automated gender detection

### ISSUE THREAD

**Issue by abhimanyu96** [python-geeks/Automation-scripts#446]
## Script Title - automated gender detection 

**Brief** - automated detection of gender of an user using their webcam 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by abhishekchopra0907** [comment]
@pawangeek can you please assign me this issue

**Comment by abhimanyu96** [comment]
@pawangeek please assign this to @abhishekchopra0907

**Comment by nauman07** [comment]
Please Assign this issue to me.
