### ISSUE TITLE
Image Super Resolution Script

### ISSUE THREAD

**Issue by NidarshN** [python-geeks/Automation-scripts#449]
Image Super Resolution Script

A Script to increase the resolution of an image using Deep Learning model

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by NidarshN** [comment]
@pawangeek Can you please assign this issue to me as i would like to contribute to the community

**Comment by nauman07** [comment]
@pawangeek can you assign this to me it would be a pleasure to serve the community.

**Comment by pawangeek** [comment]
Hey @nauman07 you can come with other ideas, this issue is already assigned

**Comment by nauman07** [comment]
@pawangeek Sir Can I add my own idea also

**Comment by pawangeek** [comment]
Yup it should be related to automating any task using Python (Duplicate and games are not allowed)

**Comment by NidarshN** [comment]
@nauman07 You are welcomed to add your own ideas. You can do so by creating a new issue and request @pawangeek to assign it to you. Looking forward for your contributions as well 👍🏻
