### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#453]
## Script Title - GUI for calculating BMI

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Shahzeb-A** [comment]
Hi, I can do this 
Can you assign this to me?

**Comment by HimadriPathak** [comment]
Hi, Can I also make a pull request for this?

**Comment by pawangeek** [comment]
Sure @HimadriPathak

**Comment by tausiq2003** [comment]
should I contribute

**Comment by avyayjain** [comment]
can i make a pull request

**Comment by Aryan810** [comment]
Hello, 
I will do this project properly, the GUI will be user friendly and clean.
You can assign it to me.

#hacktoberfest
#open-source 

Thanks!

**Comment by krishnasharma1386** [comment]
Hi!, I would like to work on this, is there any space remaining for me?

**Comment by avyayjain** [comment]
i would like to contribute to this issue pls assign me this issue
