### ISSUE TITLE
CPU Temprature detector

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#454]
## Script Title - python script to get CPU temperature 

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Shahzeb-A** [comment]
Hi, I can do this
Can you assign this to me?

**Comment by Shahzeb-A** [comment]
@pawangeek  could you check my pull request?

**Comment by pawangeek** [comment]
> @pawangeek could you check my pull request?

you have to make PR here

**Comment by Shahzeb-A** [comment]
Done ! Can u check it now?

**Comment by TheFenrisLycaon** [comment]
Is this one available?

**Comment by pawangeek** [comment]
Yup it is @TheFenrisLycaon

**Comment by TheFenrisLycaon** [comment]
I'd like to work on it.

**Comment by TheFenrisLycaon** [comment]
@pawangeek please check and merge.
