### ISSUE TITLE
JPG to png image convertor

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#455]
## Script Title - Should convert image format(.jpg) to (.png)

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Ambujbharati** [comment]
hey @pawangeek , can i work on this problem?
