### ISSUE TITLE
Document Summarizer

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#456]
## Script Title - Summarize the whole document

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by alankarartist** [comment]
Also what type of document it should be??? DOCX or PDF etc.

**Comment by pawangeek** [comment]
> Also what type of document it should be??? DOCX or PDF etc.

Better if support both, or prepare for doc and later club with this #365
