### ISSUE TITLE
Google Meet schedular

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#457]
## Script Title - Schedule a meeting

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Bhanudeep** [comment]
Assign me to this.

**Comment by Bhanudeep** [comment]
I have perform these changes
#466 
you can refer this pull request i request you to accept this.

**Comment by Aniket-508** [comment]
Can I take up this issue?

**Comment by pawangeek** [comment]
Sure @Aniket-508

**Comment by avyayjain** [comment]
can you pls assign me this task
