### ISSUE TITLE
Image background subtractor

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#458]
## Script Title - Remove background from images

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by krishnakanthati** [comment]
Hi @pawangeek, can you please assign me this?

**Comment by avats101** [comment]
@krishnakanthati are you still working on this issue it has been 4 days?
