### ISSUE TITLE
Markdown viewer

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#459]
## Script Title -

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kaliappan01** [comment]
@pawangeek can you  please assign this to me?

**Comment by pawangeek** [comment]
Cool go ahead @kaliappan01

**Comment by dipanshparmar** [comment]
Hey @pawangeek! What's the idea behind the script? Like we give it a .md file and it outputs that .md file in terminal as we see in markdown viewers?

**Comment by dipanshparmar** [comment]
Hey @pawangeek! This issue seems to be inactive for a long. May I take this?
