### ISSUE TITLE
Site blocker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#460]
## Script Title -

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by ujjwaltwitx** [comment]
@pawangeek  could assign this issue to me. I am new to open source and I would love working on this.

**Comment by ujjwaltwitx** [comment]
@pawangeek  please assign this issue to me. I want to work on this feature.

**Comment by pawangeek** [comment]
Sure @ujjwaltwitx go ahead :)

**Comment by ujjwaltwitx** [comment]
Thanks.

**Comment by ujjwaltwitx** [comment]
Feeling great after making my first contribution to open source

**Comment by ujjwaltwitx** [comment]
Can I work on improving the script?

**Comment by pawangeek** [comment]
Congrats, many more to come :)

**Comment by ujjwaltwitx** [comment]
Thanks bhaiya.
