### ISSUE TITLE
Slideshare downloader

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#461]
## Script Title -

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by LetsGetStartedWithBub** [comment]
Hi, I would like to work on this issue. I am new in open source but thought to start from here. Can I work on this issue ?

**Comment by LetsGetStartedWithBub** [comment]
Hi, I have created a pull request can you please review it.
