### ISSUE TITLE
Train pnr status checker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#462]
## Script Title -

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by hetalshah03** [comment]
Can you please assign it to me? Also, a doubt regarding this, should i create dummy databases?

**Comment by pawangeek** [comment]
You can, for testing

**Comment by hetalshah03** [comment]
initally i'll try to do it with list. Later on I'll introduce databases.

**Comment by nikhilisaac** [comment]
@pawangeek  hey can you assign me this issue . I would like to work on this using REGEX

**Comment by nikhilisaac** [comment]
do you need it with the api to check with the actual database of indian railways or just with a local database

**Comment by pawangeek** [comment]
If there is any free workaround/api, to see on actual indian railways, it will be more good, else go with a local one
