### ISSUE TITLE
Youtube video downloader

### ISSUE THREAD

**Issue by SiddhanthNB** [python-geeks/Automation-scripts#483]
## Script Title -you_thub

**Brief** - A script that downloads youtube video from its link with user's desired resolution.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by khoinguyen-hub** [comment]
Hi, this is my first time doing open-source, and I'd like to tackle this issue.

**Comment by SiddhanthNB** [comment]
@pawangeek please assign this to me.

**Comment by pawangeek** [comment]
We already have one #159

**Comment by SiddhanthNB** [comment]
Alright, my bad.
