### ISSUE TITLE
Password generator

### ISSUE THREAD

**Issue by dipanshparmar** [python-geeks/Automation-scripts#485]
## Script Title - Password Generator

**Brief** - A script to generate random passwords with the following criteria:
- Include symbols
- Include numbers
- Include lowercase characters
- Include uppercase characters
- exclude similar characters

### Programming Language
- [x] Python

**Comment by dipanshparmar** [comment]
Hey @pawangeek, can you please assign this to me?

**Comment by tausiq2003** [comment]
Can I add a password generator file to this for hacktoberfest2021
