### ISSUE TITLE
Automatically play the created audio file in `audio_book/PDF_TO_AUDIO.py`

### ISSUE THREAD

**Issue by Saransh-cpp** [python-geeks/Automation-scripts#491]
It would be nice to automatically play the generated audio in [`audio_book/PDF_TO_AUDIO.py`](https://github.com/python-geeks/Automation-scripts/blob/main/audio_book/PDF_TO_AUDIO.py) to make the panda lazier. I'd like to work on this, if it is something that everyone thinks should be added up.

**Comment by pawangeek** [comment]
It should be user-driven, like if someone don't want to listen at that time, we shouldn't play it automatically.
