### ISSUE TITLE
Add a way to highlight the detected text in `text_from_image/main.py`

### ISSUE THREAD

**Issue by Saransh-cpp** [python-geeks/Automation-scripts#493]
Right now the file OCRs the image but doesn't highlight the captured text. Something like this -

![OCR](https://user-images.githubusercontent.com/74055102/135517824-ac073bfb-c81b-4cd2-b167-7524e9580054.png)
 

Plus the code isn't very user-friendly and does not follow flake8 linting. I'd like to take this up!

**Comment by pawangeek** [comment]
Ohk, do that :)
