### ISSUE TITLE
AQI Tracker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#494]
## Script Title - Script should able to tell the aqi (air quality index) 
(Hint: There are many free APIs to do that)

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by itsanshulverma** [comment]
I would love to work on this, please assign it to me.

**Comment by pawangeek** [comment]
Sure, go ahead :)
