### ISSUE TITLE
Auto Backup the folder/folders

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#495]
## Script Title - Script which takes the path and time to start backup

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by TheFenrisLycaon** [comment]
I would like to take this up.

**Comment by pawangeek** [comment]
Cool, take it up

**Comment by TheFenrisLycaon** [comment]
Okay

**Comment by TheFenrisLycaon** [comment]
@pawangeek please check and merge.

**Comment by TheFenrisLycaon** [comment]
@pawangeek this is completed.
