### ISSUE TITLE
Extracting audio from videos

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#497]
## Script Title - Script able to extract audio from video and save it in desired folder

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by DevChoganwala** [comment]
Hey @pawangeek, I would like to work on this issue!!

**Comment by TheFenrisLycaon** [comment]
Can I work on this?

**Comment by avyayjain** [comment]
pls assign me this issue
