### ISSUE TITLE
Sort Bulk Files Automation

### ISSUE THREAD

**Issue by JaniniRami** [python-geeks/Automation-scripts#499]
Sort Bulk Files Automation

**Brief** -
The script will be run in a folder full of random files and sort them based on there file types and names in each separate folder.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pawangeek** [comment]
Hey, isn't it same as #219 ?

**Comment by JaniniRami** [comment]
Yes I closed it and opened a new issue with a new script idea.
