### ISSUE TITLE
HTMLtoPDF maker

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#5]
## Script Title - Convert html to pdf

**what will change** - Adding script of it

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by parth93QA** [comment]
can u assign me this ?

**Comment by pawangeek** [comment]
Sure :)
