### ISSUE TITLE
Converting text to sound

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#50]
## Script Title - Script to convert text to sound

**what will change** - Adding script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Anustup900** [comment]
Hello please assign to me

**Comment by pawangeek** [comment]
Sure, go ahead :)

**Comment by SaiSrichandra** [comment]
Can I also give it a shot?

**Comment by pawangeek** [comment]
Sorry @SaiSrichandra, Please look into other issues. This is already assigned to someone. You can create your own issue too for any practical application. Hope you understand :)
