### ISSUE TITLE
CPU info script

### ISSUE THREAD

**Issue by Somanyu** [python-geeks/Automation-scripts#502]
## Script Title - System Information

**Brief** - Sometimes while working you want to know about the CPU usgae of your computer or how many memory is your computer consuming and other various reasons where you need to know about your hardware and system.
Python has a awesome library [*psutil*](https://github.com/giampaolo/psutil) which displays information on processes and system like CPU, memory, disks, etc.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by geethakrishna25** [comment]
Hi can, i work on this issue

**Comment by TheFenrisLycaon** [comment]
I would like to take this one.

**Comment by Somanyu** [comment]
can you assign this @pawangeek
