### ISSUE TITLE
Random email name generator

### ISSUE THREAD

**Issue by pankaj892** [python-geeks/Automation-scripts#512]
## Script Title - Random email name generator

**Brief** -
This script generates random email names with domain names as per the required number of emails user inputs
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by R055A** [comment]
Requesting being assigned, please

**Comment by Aniket-508** [comment]
Can I work on this please?

**Comment by pankaj892** [comment]
@pawangeek Can you assign me to work on this ?

**Comment by R055A** [comment]
> 
> 
> Hey guys, the one added the script idea, will be assigned, @pankaj892 go ahead :)

I see now, thank you.

**Comment by pawangeek** [comment]
> > Hey guys, the one added the script idea, will be assigned, @pankaj892 go ahead :)
> 
> I see now, thank you.

Meanwhile, I am adding some more issues, you can check and work on any of them
