### ISSUE TITLE
Expense manager

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#514]
## Script Title - Simple GUI program to manages expenses

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Aniket-508** [comment]
Can you please assign me this?

**Comment by pawangeek** [comment]
Sure, you can take this

**Comment by Aniket-508** [comment]
@pawangeek Do I have to provide backend database file also or just the GUI frontend part file works?

**Comment by pawangeek** [comment]
There should be database else how should one keep track of all till now?
