### ISSUE TITLE
Currency conversion rate

### ISSUE THREAD

**Issue by Aniket-508** [python-geeks/Automation-scripts#515]
## Script Title - Currency conversion rate

**Brief** -
You’ve probably looked up conversion rates using your browser, but we can automate the task of finding the current exchange rate between any two currencies.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Aniket-508** [comment]
@pawangeek hey, can I work on this?

**Comment by pawangeek** [comment]
Hey @Aniket-508 #69 it's already in Repo :(
