### ISSUE TITLE
Image Encoder

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#516]
## Script Title - simple program to encode and decode images, which helps to reduce and handle images on server, as it is converted to base64 address.

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by gokhalevedant06** [comment]
Hi, output should be an image URI right  ?

**Comment by pawangeek** [comment]
Exactly, you can use a key-value pair even to store in json format

**Comment by gokhalevedant06** [comment]
Okay! Can I try this?

**Comment by pawangeek** [comment]
Yeah, why not

**Comment by SwarajBaral** [comment]
hey @pawangeek can I take it up ? I am pretty new to open source and I am starting out with hacktoberfest 2021. Even though it has been assigned, can I work on it ?

**Comment by pawangeek** [comment]
> hey @pawangeek can I take it up ? I am pretty new to open source and I am starting out with hacktoberfest 2021. Even though it has been assigned, can I work on it ?

Well @SwarajBaral one issue need one PR, if your PR doesn't get closed, it won't marked as contribution, it's better to work on separate script

**Comment by SwarajBaral** [comment]
> > hey @pawangeek can I take it up ? I am pretty new to open source and I am starting out with hacktoberfest 2021. Even though it has been assigned, can I work on it ?
> 
> Well @SwarajBaral one issue need one PR, if your PR doesn't get closed, it won't marked as contribution, it's better to work on separate script
Oh, okay then @pawangeek, I will be looking out for new issue for a new script idea, then. Thanks for the reply.

**Comment by zatch3301** [comment]
can i do it too?
