### ISSUE TITLE
Retweet bot

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#517]
## Script Title - Simple script that retweets any hashtag provided in it.

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by thevirtualbuddy** [comment]
Hi @pawangeek , Can I work on this issue?

**Comment by pawangeek** [comment]
Sure, go ahead
