### ISSUE TITLE
Desktop break notifier

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#518]
## Script Title - Script able to enable toast notification for break in every 15/20 minutes to avoid being on computer continuously
 
**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by dipanshparmar** [comment]
@pawangeek can you please assign this to me?
