### ISSUE TITLE
Url Shortner

### ISSUE THREAD

**Issue by bartick** [python-geeks/Automation-scripts#522]
## Script Title - Url Shortner

**Brief** - The script with make the script smaller for easier usage

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pawangeek** [comment]
same as #7

**Comment by TheFenrisLycaon** [comment]
Can I work on this?
