### ISSUE TITLE
email-phone-extractor

### ISSUE THREAD

**Issue by itsanshulverma** [python-geeks/Automation-scripts#527]
## Script Title - email-phone-extractor

**Brief** -
Extract emails and phone numbers from the text from clipboard, to the clipboard

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by itsanshulverma** [comment]
Please validate and assign it to me

**Comment by pawangeek** [comment]
So it will based on regex right?

**Comment by itsanshulverma** [comment]
yes

**Comment by pawangeek** [comment]
okay, that's fine but make it bit more extensive, like it should save emails and numbers separately in two different csv/excel. And take a text file too as input not just text in terminal, Hope you got it :)

**Comment by gitshashwat** [comment]
Hey @pawangeek , Looks interesting! Can you assign this to me too?
