### ISSUE TITLE
Customizable Webapp-Login Templates

### ISSUE THREAD

**Issue by VaishnaviNandakumar** [python-geeks/Automation-scripts#528]
## Script Title -
Flask-WebApp-Login Templates

**Brief** -
Script that creates customizable login and registration templates using Flask and MongoDB for any web app project.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by VaishnaviNandakumar** [comment]
@pawangeek  I'd like to contribute to this project.

**Comment by pawangeek** [comment]
Okay go ahead :)

**Comment by VaishnaviNandakumar** [comment]
@pawangeek Hi. I'm facing a small issue with flake8. My project using the '@wraps' decorator which doesn't require indentation but the it always raises a warning of 'E111 indentation is not a multiple of 4'. Is there anything I can do to disregard it?

**Comment by pawangeek** [comment]
Yup add #noqa at the end of that particular line

**Comment by VaishnaviNandakumar** [comment]
@pawangeek Thanks! I've created a pull request.
