### ISSUE TITLE
Image to sketch

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#53]
## Script Title - Able to convert any image to sketch (Use cv2 module for that)

**what will change** - Adding script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by janethavi** [comment]
Can I get assigned for this issue?

**Comment by pawangeek** [comment]
okay, sure

**Comment by fieryash** [comment]
Can I get assigned for this issue as well? Or is it 1 person per issue only?

**Comment by pawangeek** [comment]
Just one issue per person @fieryash
