### ISSUE TITLE
credit_card_validator

### ISSUE THREAD

**Issue by kuspia** [python-geeks/Automation-scripts#531]
## Script Title - credit_card_validator

**Brief** - I will be writing the code to validate the credit cards to find out whether it is correct or not, also it will find the card type

Importance:
It is important to keep in mind that whenever fraudulent cards are used, the merchant loses. If too many fraudulent transactions occur, you may incur higher processing fees, expensive chargebacks, or even losing your merchant account and your ability to do business.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kuspia** [comment]
Kindly assign this issue to me, I would like to work it on this from scratch.
Note #530 was opened by me but using another account so I closed that.

**Comment by pawangeek** [comment]
Okay, go ahead :)

**Comment by avyayjain** [comment]
pls can you assign me with this issue I want to work on it

**Comment by kuspia** [comment]
hi kindly check @pawangeek and please merge it
