### ISSUE TITLE
Battery Automation Script

### ISSUE THREAD

**Issue by pankaj892** [python-geeks/Automation-scripts#532]
## Script Title - Battery Automation 

**Brief** -
This script notifies the user about the remaining battery left based on the threshold provided by user
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pankaj892** [comment]
@pawangeek can I work on this ?

**Comment by SwarajBaral** [comment]
Hey @pawangeek I would like to work on this as well.
