### ISSUE TITLE
Horoscope

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#533]
## Script Title - Script able to tell horoscope of the daily by zodiac sign

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kshittijagrawal** [comment]
Hey @pawangeek !
I would love to work on this issue. Could you assign this to me?
