### ISSUE TITLE
Automation Script Converting Video File into an Audio File.

### ISSUE THREAD

**Issue by kshittijagrawal** [python-geeks/Automation-scripts#534]
## Script Title - Audio Visual to Audial

**Brief** - This script converts any kind of video file format to its equivalent audio file format.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kshittijagrawal** [comment]
Hey @pawangeek !
I would like to add this script into your repository. If you'd like me to do so, kindly assign me this issue. :)

**Comment by pawangeek** [comment]
Already in progress #497
