### ISSUE TITLE
Straighten image

### ISSUE THREAD

**Issue by Saransh-cpp** [python-geeks/Automation-scripts#535]
## Script Title - A script to straighten up an image (for preprocessing purposes, can be used before OCRing an image)
**Brief** -
The script will basically rotate an image to straighten it up. Example (note that in the second image, the image has been tilted in a way that makes the book straight) - 

<p float="left">
<img src="https://user-images.githubusercontent.com/74055102/135614541-01f8ef65-de92-453b-b288-e81fa5dbe164.jpg" height=500/>
<img src="https://user-images.githubusercontent.com/74055102/135614855-b81844c7-d1fd-47f8-99fe-5141751abd7b.png" height=500/>
</p>

I'd like to take this up!

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kapshar** [comment]
Hey @Saransh-cpp, I would like to work on this script can you assign this issue to me.

**Comment by Saransh-cpp** [comment]
Hi @kapshar, I am not a maintainer here. I am myself looking out to work on this issue :)
> I'd like to take this up!
