### ISSUE TITLE
Crypto Currency

### ISSUE THREAD

**Issue by jayaganeshkumar** [python-geeks/Automation-scripts#537]
## Script Title -
CryptoCurrency

**Brief** -
A python script to get the top 100 crypto coins details from the coin market website and store them in a CSV file. A crypto coin symbol will be taken as input and the details of that coin will be stored in another CSV. Here details include: name, symbol, website, price(current), all-time highest price, etc. I already have the code ready.
## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by jayaganeshkumar** [comment]
@pawangeek can you assign this to me?

**Comment by pawangeek** [comment]
Hey its already in progress #536

**Comment by jayaganeshkumar** [comment]
@pawangeek it's not a tracker. It just stores the top 100 crypto names along with their sites in the coin market. If we give any coin's symbol as input it will return the details like name, price, websites, all-time highest and all.

**Comment by pawangeek** [comment]
Ohk sounds different then
