### ISSUE TITLE
Scraping links from Text file

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#54]
## Script Title - Able to extract all links from any text file (Use regex library)

**what will change** - Add script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by DevMahmoud10** [comment]
Can I work on it?

**Comment by pawangeek** [comment]
sure, go ahead :)
