### ISSUE TITLE
Mask Detection

### ISSUE THREAD

**Issue by anubhav201241** [python-geeks/Automation-scripts#540]
## Script Title - Mask Detection

**Brief** -
I wanted to contribute to your repository Mask Detection using open cv and python 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pawangeek** [comment]
Hey, isn't it similar to #216

**Comment by avyayjain** [comment]
pls assign me this issue
