### ISSUE TITLE
Script to send a Discord embedded message via a webhook

### ISSUE THREAD

**Issue by OjusWiZard** [python-geeks/Automation-scripts#541]
## Discord Embedded Message from a Webhook -

**Brief** - A Discord webhook is an API interface, my code will be sending an HTTP request to this webhook with a message payload in a specific JSON form. This payload will be interpreted by discord and show it in Embedded form as a message in the channel.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by madrigal1** [comment]
hey am interested, can you expand on the specific JSON format ?
also if you are comfortable in share any communication info as discord/ discord channel would be helpful
