### ISSUE TITLE
Text Encryptor and Decryptor using AES

### ISSUE THREAD

**Issue by sudesh1611** [python-geeks/Automation-scripts#548]
## Script Title - Text Encryptor and Decryptor using AES

**Brief** - A script which will encrypt/decrypt the text using the password.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by sudesh1611** [comment]
@pawangeek  Can you please assign this to me

**Comment by brandon-1999** [comment]
Yoo this will be fun. ill give this a go. What do you suggest the return should be?

[[<duplicate file paths _array_>,<entries _int_>,<hash of files _string_>], ... ]?

This will be the first time i ever work on anything within github so feedback is really appreciated :)

**Comment by pawangeek** [comment]
@sudesh1611 Isn't it same as #142 ?

**Comment by sudesh1611** [comment]
Ohh. Didn't see that. Let me change the issue then

**Comment by pawangeek** [comment]
Well this is new :)
