### ISSUE TITLE
Sending SMS

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#55]
## Script Title - Script is able to send msgs (Use Twilio or SendGrid for that)

**what will change** - Adding script for sending sms

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by YourFriendlyError** [comment]
May I work on this?

**Comment by pawangeek** [comment]
Sure,  why not?
