### ISSUE TITLE
Simple Slack Mesage

### ISSUE THREAD

**Issue by danangharissetiawan** [python-geeks/Automation-scripts#554]
## Script Title - Slack Message

**Brief** - a script to send messages on slack automatically

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by ilmalte** [comment]
I would be happy to take it! 😄

**Comment by rahulbhatt1899** [comment]
Hey, I'd like to contribute!
