### ISSUE TITLE
Scraping Github user details

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#56]
## Script Title - The purpose of the script is to get publicly available detail from user account

**what will change** - Adding script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by michalStarski** [comment]
Can you assign me to this issue? I'd like to contribute.

**Comment by pawangeek** [comment]
Sure, go-ahead
