### ISSUE TITLE
Folder Automator

### ISSUE THREAD

**Issue by decipher07** [python-geeks/Automation-scripts#564]
## Script Title -

**Brief** - This Script is useful in case, You have a messed with a lot of files in any of your directories. In Such cases, Finding a document may be tedious depending on the extension and search time used by your OS. 

This Script compiles all your similar file extensions into their respective folders without any extra dependencies.

You just need to run script.py run the script.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by decipher07** [comment]
Can you please let me add my script?
Thank You,
Happy Contributing

**Comment by pawangeek** [comment]
Isn't it similar to #219 ?

**Comment by decipher07** [comment]
Yeah, You are right!, Maybe I will think of something new then. 
Thanks Again
Happy Contributing
