### ISSUE TITLE
Codeforces scraper

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#569]
## Script Title - Script able to scrape the cf question

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by decipher07** [comment]
Can I please work on this?

**Comment by pawangeek** [comment]
Sure :)
