### ISSUE TITLE
Color to black-n-while image

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#57]
## Script Title - Script is able to change a color image to bw image (Can be done by cv2 library)

**what will change** - Adding script for that

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by fieryash** [comment]
Is this a simple script for black and white or is there any special condition?
I am creating a pull request for this issue.

**Comment by YourFriendlyError** [comment]
May work on this?

**Comment by pawangeek** [comment]
Just a simple task for changing the color of the image to bw and save it too
