### ISSUE TITLE
PDF particular page remover

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#572]
## Script Title - Using this script one can delete the pages with just one click.

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by sighclone** [comment]
I'll take this up!

**Comment by pawangeek** [comment]
Cool go ahead :)

**Comment by sighclone** [comment]
Hi! I have completed solving the issue and have raised a PR.
