### ISSUE TITLE
Sticky notes

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#573]
## Script Title - A simple GUI based application in Python that helps you to create simple remember lists or sticky notes.

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by SwarajBaral** [comment]
hey @pawangeek i would like to take this up. Can you assign me this ?

**Comment by SwarajBaral** [comment]
@pawangeek I have created the required PR for this issue. Kindly check #594.
