### ISSUE TITLE
Audio notes

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#574]
## Script Title - Sticky notes with user audio input as feature

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by sighclone** [comment]
Hi, I'd like to take this issue up!

**Comment by sighclone** [comment]
Hi again! I have completed solving the issue and have raised a PR (#588).
