### ISSUE TITLE
IPL Status

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#58]
## Script Title - Webapp able to fetch the next matches and score if any match is live

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by HolgerDoerner** [comment]
Hello, I would like to take this one for HacktoberFest :smiley:
