### ISSUE TITLE
Empty Folder Cleaner

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#59]
## Script Title - Scriptable to remove all empty folders from target directory

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by javmarina** [comment]
Can you assign it to me?

**Comment by pawangeek** [comment]
ok, fine
