### ISSUE TITLE
fancy_text_generator

### ISSUE THREAD

**Issue by kuspia** [python-geeks/Automation-scripts#591]
## Script Title - fancy_text_generator

**Brief** -
The script will ask the user to enter a text which will be converted into fancy texts.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kuspia** [comment]
i woul dlike to work on this feature addition kindly assign me

**Comment by muneersyed156** [comment]
Can you please assign this to me
