### ISSUE TITLE
Crypto Currency Datasets fetcher

### ISSUE THREAD

**Issue by avats101** [python-geeks/Automation-scripts#597]
## Need
Currently in the crypto folder there is no script to fetch data for a particular coin. I plan to do so using some APIs and download the dataset locally which could be used for EDA/ predictions.

### Programming Language

- [x] Python

**Comment by pawangeek** [comment]
#537 It's already done

**Comment by avats101** [comment]
I think thats for top 100 coins on a day. My script could be used for any coin

**Comment by pawangeek** [comment]
Still, almost same
