### ISSUE TITLE
Sudoku solver

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#6]
## Script Title - Sudoku Solver by recursion/backtrack

**what will change** - Adding script for solving sudoku

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by jp2373** [comment]
I would love to work on this, can you please assign it to me?

**Comment by zmunro** [comment]
@jp2373 just fork the repo and start working on it :)

**Comment by jayaganeshkumar** [comment]
@pawangeek  I have this code ready. Can you assign it to me?

**Comment by pawangeek** [comment]
Okay, I am assigning this to you @jayaganeshkumar
