### ISSUE TITLE
Alarm Clock

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#60]
## Script Title - Script is able to make a particular sound on set time
(You can use winsound and sched module for this)

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by SoumyaRanjanNaik** [comment]
Can I build a command line alarm clock ?
If yes, can I have this issue assigned to me ?

**Comment by avishekchoudhary** [comment]
Can you assign it to me also

**Comment by pawangeek** [comment]
okay go ahead
