### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by Tejaswi-Kumar** [python-geeks/Automation-scripts#603]
## Script Title - Real-time Face Recognition 

**Brief** - A python script for recognizing a real-time familiar face from a library of faces stored in a device.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Tejaswi-Kumar** [comment]
I want to work on this issue, please assign it to me.

**Comment by aarshita02** [comment]
Hey, my code is ready for the same. Can you please assign it to me so that I can make a pull request for the same?

**Comment by avyayjain** [comment]
pls assign me this
