### ISSUE TITLE
chatbot

### ISSUE THREAD

**Issue by pembattech** [python-geeks/Automation-scripts#604]
## Chatbot-

**A simple Chatbot** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pccoder-2000** [comment]
can I work on this issue?

**Comment by Kiinitix** [comment]
Hey, my code is ready for the same. Can you please assign it to me?

**Comment by avyayjain** [comment]
pls assign me this issue
