### ISSUE TITLE
URL_shortner

### ISSUE THREAD

**Issue by avats101** [python-geeks/Automation-scripts#606]
## URL_shortner

**Brief** -
Currently the code in this colletion is based only on TinyURL,I plan to implement it based on any URL shortner based on User's preference.
Current code in this repo-[Link](https://github.com/python-geeks/Automation-scripts/blob/main/url_shortener/url.py)

### Programming Language

- [x] Python

Happy Coding

**Comment by avats101** [comment]
@pawangeek  Please assign me this improvement issue.

**Comment by pawangeek** [comment]
Can you please elaborate more what do you mean by user preference?

**Comment by avats101** [comment]
Every user wont prefer to have a URL based on tinyURL some may prefer other packages(based on pricing and ease of use)

**Comment by pawangeek** [comment]
Still same concept
