### ISSUE TITLE
Multi-mode GUI Calculator using Python

### ISSUE THREAD

**Issue by sandipan898** [python-geeks/Automation-scripts#607]
## Multimode GUI Calculator using Python

**A GUI based Multi-mode calculator application using python. It has two interfaces based on two different modes: Simple and Scientific, that includes all the simple as and scientific calculation functionalities. User can switch between different modes** 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by krishnakanthati** [comment]
Hi @pawangeek, can you please assign me this?

**Comment by krishnakanthati** [comment]
@sandipan898 Can I use Flask for this?

**Comment by pawangeek** [comment]
> @sandipan898 Can I use Tkinter for this?

Yes, you can

**Comment by sandipan898** [comment]
> @sandipan898 Can I use Tkinter for this?

I'm already done with the project with all set to create a PR
