### ISSUE TITLE
Add a Crypto Currency Converter Script to the set of Crypto folders.

### ISSUE THREAD

**Issue by kshittijagrawal** [python-geeks/Automation-scripts#610]
## Script Title - Crypto Currency Converter

**Brief** - Create a script that converts the most frequently used crypto currencies into its equivalent fiat (government issued) currencies.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pawangeek** [comment]
Sure, go ahead :)
