### ISSUE TITLE
YAML to JSON Converter

### ISSUE THREAD

**Issue by SoniGarima** [python-geeks/Automation-scripts#624]
## YAML to JSON Converter

The python program will convert given Yaml file into Json file.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by moazfarrukh** [comment]
can i work on this?

**Comment by pawangeek** [comment]
Okay go ahead :)

**Comment by moazfarrukh** [comment]
@pawangeek i have made the pull request awaiting review

**Comment by SoniGarima** [comment]
Well I opened this issue because obviously I was working on it. But it's okay have a good day :)

**Comment by moazfarrukh** [comment]
> Well I opened this issue because obviously I was working on it. But it's okay have a good day :)

Oh sorry i am new to contributing to to github repos. I might have misunderstood. I thought instructions are only given in the issue if its for others to solve.

**Comment by SoniGarima** [comment]
That's totally fine. I just have one more point. In yaml files, generally those used during deploying applications on kubernetes cluster, There often exist more than one components separated by `---`. I think you should modify your code to convert that into json also. Happy Coding :)
