### ISSUE TITLE
Add a Hacker News Scraper script.

### ISSUE THREAD

**Issue by kshittijagrawal** [python-geeks/Automation-scripts#625]
## Script Title - hackernews_scraper

**Brief** - A script that scrapes the exact count of news that the user demands and stores it in a csv file.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kshittijagrawal** [comment]
Hey @pawangeek !
Can I work on this script?

**Comment by pawangeek** [comment]
possible duplicate of #548

**Comment by kshittijagrawal** [comment]
Oh
Sorry I didn't notice. Let me edit the issue.
