### ISSUE TITLE
Scraping BBC and CNN News website

### ISSUE THREAD

**Issue by GudlaArunKumar** [python-geeks/Automation-scripts#63]
## Script Title - Scraping the first two pages of HackerNews website 

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by GudlaArunKumar** [comment]
Can I work on this issue @pawangeek

**Comment by pawangeek** [comment]
Hey, can you able to scrape CNN and BBC in if-else condition? That's more useful to me. Just home page headlines ?

**Comment by GudlaArunKumar** [comment]
Okay sure, I will try CNN and BBC scraping after completing this script. Is that fine?

**Comment by GudlaArunKumar** [comment]
okay then as you changed the title, I will do BBC and CNN then!

**Comment by pawangeek** [comment]
Yeah sure :)
