### ISSUE TITLE
Image Downloader

### ISSUE THREAD

**Issue by FireHead90544** [python-geeks/Automation-scripts#631]
## Script Title - Image Downloader

**Brief** - A script which downloads and saves the image locally, provided the link to the image.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- Python

Happy Coding

Please, I wanna claim this one, and after completing this I have one more in mind. Let me claim this one please. Thanks :)

**Comment by FireHead90544** [comment]
Lemme claim this one please :D 
Thanks

**Comment by milk-mann** [comment]
I'd also really like to take this issue smile
