### ISSUE TITLE
IMAGE TO SKETCH CONVERTER

### ISSUE THREAD

**Issue by Richa812** [python-geeks/Automation-scripts#632]
## IMAGE TO SKETCH CONVERTER USING PYTHON AND OPENCV

**It is an interesting project where any image can be coverted to a sketch . 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Richa812** [comment]
May I work on this issue?

**Comment by pawangeek** [comment]
> May I work on this issue?

Duplicate of #108
