### ISSUE TITLE
Some more Automation Script ideas 

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#636]
If anyone out of ideas, can pick from here 😀 

**Note 1: Ticked are picked or completed**
**Note 2: Create a issue with any idea to work on**

- [x] Calendar GUI
- [x] PNG to jpg convertor
- [x] Make image corners round
- [x] Eye Detection
- [x] Image to speech (voice) 
- [x] Morse code Translator
- [x] PPT to Video
- [x] Tkinter Python GUI
- [x] Subtitle Downloader
- [x] CSV to excel
- [x] CSV to JSON
- [x] Excel to CSV
- [x] Algebra solver
- [x] Excel Merger
- [x] IMDB Querier
- [x] Caeser CIpher

**Comment by avats101** [comment]
@pawangeek  Hi, I would like to take the task making image corners round.

**Comment by pawangeek** [comment]
> @pawangeek Hi, I would like to take the task making image corners round.

Open up the issue, and I will assigned it to you

**Comment by durgeshahire07** [comment]
hey @pawangeek , I would like to work on CSV to JSON 
issue #693

**Comment by divyaprakashdp** [comment]
Hi @pawangeek, how about images to gif?

**Comment by TJakub** [comment]
@pawangeek Hey, u closed my issue, i dont know why, but could u make some other for me? i would like to work on something please, my last issue was #699

**Comment by CypherpunkSamurai** [comment]
Here's Some Ideas:
[ ] Make a Python3 Bot to Auto Attend Google Meet / Zoom Classes
[ ] Make a Python3 Program to Scrape ratings for movies and TV Shows (Use Squid Game for example)
[ ] Make a Python3 Bot to generate cool images from shapes and gradients. (Possible NFT generator)
[ ] Make a Python3 WebUI for youtube-dl
[ ] Make a Python3 GUI for youtube-dl
[ ] Make a Python3 Anime List management tool
[ ] Make a Python3 Websocket Chat Server
[ ] Make a Python3 Raw TCP encrypted chat
[ ] Make a Python3 ARP packet spoofer
[ ] Make a Python3 ARP network scanner

**Comment by KazushiR** [comment]
@pawangeek Is there anything that I can work on in terms of stock data?
