### ISSUE TITLE
CALENDAR GUI

### ISSUE THREAD

**Issue by Richa812** [python-geeks/Automation-scripts#644]
### Calendar GUI

**Brief** -A Calendar GUI using python and tkinter

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Richa812** [comment]
Can I get to work on this issue?

**Comment by pawangeek** [comment]
Sure, go ahead :)

**Comment by pawangeek** [comment]
> Can you please assign me this issue? I can get it done.

Sure go ahead :) you can get some idea from #679
