### ISSUE TITLE
Mass Digital Certificate Maker

### ISSUE THREAD

**Issue by salmanselu** [python-geeks/Automation-scripts#646]
## Mass Digital Certificate Maker
A python script that will automatically insert names from a CSV file into a digital certificate template

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by salmanselu** [comment]
Hi. please assign this task to me

**Comment by pawangeek** [comment]
Implement that in #344

**Comment by salmanselu** [comment]
Hi @pawangeek . I did not notice that this was already implemented. I checked it out and saw that there isn't much for me to improve. So I would not be partaking. Sorry
