### ISSUE TITLE
GUI Timer Program

### ISSUE THREAD

**Issue by kahtras665** [python-geeks/Automation-scripts#653]
## Script Title - timer_gui

**Brief** - I would like to add a gui timer application made with python using the tkinter library.
                 Kindly assign this issue to me, so that I could work on it.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by nitin-pandita** [comment]
I can do this. Please assign me

**Comment by pawangeek** [comment]
Duplicate of #637
