### ISSUE TITLE
Instagram Bot to Follow People

### ISSUE THREAD

**Issue by whynesspower** [python-geeks/Automation-scripts#658]
## Instagram Bot to follow people-

**Instagram bot to send a follow request to given set of random people, automates the task to increase your reach** -
These type of instagram bots are used extensively by small businesses on Instagram. 

##Requiments 

1. latest version of chrome
2. Selenium and Instapy module pip installed

## Instructions
instabot2.py uses Instapy module which is much faster then Selenium based bot
**Kindly add your username and password in the code file .**

### Programming Language

- [x] Python

Happy Coding =)

**Comment by pawangeek** [comment]
> > @pawangeek Hey Pawan, I made a PR for the issue and the code is well documented and working in good condition.
> > I have one quick thing to ask, flake8 is telling me that my code has imported random module but not used it, hence its giving me linting error. I am new to this. What must I do?
> 
> Just Remove the random module, If you're not using it

**Comment by pawangeek** [comment]
And you can make changes after creating the PR too

**Comment by whynesspower** [comment]
> And you can make changes after creating the PR too

I will keep that in mind from next time, for now I have created a fresh pull request which passes all the checks.
@pawangeek Please consider marking it as hacktober fest accepted!
Thankyou =)
