### ISSUE TITLE
MP4 to MP3 convertor

### ISSUE THREAD

**Issue by RaveenaBhasin** [python-geeks/Automation-scripts#660]
## Script Title -

This application will allow user to select any mp4 video and will convert it to mp3 audio.
User can also save the mp3 video to any where on the local system.

## Requirements-
Tkinter GUI, pymovie library 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by RaveenaBhasin** [comment]
Kindly assign this issue to me @pawangeek

**Comment by pawangeek** [comment]
> @pawangeek I have made the Pull Request for the same but the flake8 check is going wrong. What changes I have to make so that it can pass?

See the details there or check project README how to make flake8 compatible file
