### ISSUE TITLE
Grayscale Image Filter

### ISSUE THREAD

**Issue by ParadoxPD** [python-geeks/Automation-scripts#669]
## Script Title - Grayscale Image Filter

**Brief** - A filter to convert ***rgb*** images to ***grayscale***

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by ParadoxPD** [comment]
Assign this to me.

**Comment by pawangeek** [comment]
Duplicate of #57
