### ISSUE TITLE
Scrape all URLs from a Website

### ISSUE THREAD

**Issue by kahtras665** [python-geeks/Automation-scripts#677]
## Script Title - url_scraper.py

**Brief** - This is a python script which uses two libraries beautfulsoup4 and requests to scrape a website and find all the URLs the website could redirect to. 
For example:- The links the website could redirect the user to in the form of a button or a hyperlink.
Kindly assign this issue to me, so that I can work on it!
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Gud-will** [comment]
hi
I noticed that this issue has been open for about 23 days, so as the author has not yet closed the issue, so can u please assign this issue to me.
I have completed working on this issue

**Comment by sighclone** [comment]
@pawangeek Hi, I think @Gud-will (Author of above comment) has forgotten to mention @ you and you weren't notified. Or is this issue still held by the original assignee?

**Comment by pawangeek** [comment]
> hi
> I noticed that this issue has been open for about 23 days, so as the author has not yet closed the issue, so can u please assign this issue to me.
> I have completed working on this issue

Go ahead @Gud-will complete it asap :)
