### ISSUE TITLE
Quick Sort Visualizer using Tkinter GUI

### ISSUE THREAD

**Issue by RaveenaBhasin** [python-geeks/Automation-scripts#687]
## Script Title - Quick Sort Visualizer

**Brief** - A visualizer made using Python to see the working of the quick sort algorithm.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by niits** [comment]
@RaveenaBhasin may I take this issue?
