### ISSUE TITLE
Tkinter Python GUI

### ISSUE THREAD

**Issue by mgndolan** [python-geeks/Automation-scripts#696]
## Tkinter Python GUI

A cross-platform Python GUI application with Tkinter. Suggestion from #636 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by zainulabideen1122** [comment]
Have a look at: 
https://github.com/zainulabideen1122/Currency_Converter_App
