### ISSUE TITLE
Excel to CSV

### ISSUE THREAD

**Issue by TJakub** [python-geeks/Automation-scripts#699]
## Script Title - Excel to CSV

**Brief** -  Aim to create a Python script to convert Excel to CSV

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by alainseys** [comment]
@TJakub 

If no solution is provided yes i can make a PR for this
