### ISSUE TITLE
URL shortener

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#7]
## Script Title - Creating URL shortener by changing base and using map/dict

**what will change** - Adding URL shortener script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by hpnightowl** [comment]
can i take this issue?

**Comment by pawangeek** [comment]
Sure go ahead

**Comment by hpnightowl** [comment]
in this task i have to make a custom url shortener or i can use tinyurl api @pawangeek

**Comment by pawangeek** [comment]
You can make it by any means. Just document it with README and requirements

**Comment by hpnightowl** [comment]
ok :)
