### ISSUE TITLE
Face morphing

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#70]
## Script Title - Script is able to create a small gif converting one face to another (One can use Delaunay triangulation + Warp affine and cv2 module for this)

**what will change** - Adding a script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding,

**Comment by Anustup900** [comment]
I want to work in this issue too please assign me

**Comment by pawangeek** [comment]
Can you please send a PR of the previously assigned issue?

**Comment by Anustup900** [comment]
> Can you please send a PR of the previously assigned issue?

yes am just creating the pull request in one hour

**Comment by pawangeek** [comment]
Sure, then I will assign this to you :)

**Comment by Anustup900** [comment]
I created the PR , and its now passed tests can you please assign to me

**Comment by pawangeek** [comment]
sure, you deserve it
