### ISSUE TITLE
Time zone conversion

### ISSUE THREAD

**Issue by PriyankaHotchandani** [python-geeks/Automation-scripts#731]
## Time Zone Conversion

**Brief** - Python script that converts a time from one time zone to another

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by alexaraiza** [comment]
Can I have this issue assigned to me, please?

**Comment by AndrasBard** [comment]
Would you like to assign this issue to me?
