### ISSUE TITLE
Algebra Solver GUI

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#732]
## Script Title - By using sympy

**Brief** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by deepakdinesh1123** [comment]
can I take this issue?

**Comment by pawangeek** [comment]
> can I take this issue?

Sure

**Comment by deepakdinesh1123** [comment]
I started working on the issue, I implemented basic UI using pysimplegui but the task was a little vague. Can you please elaborate more about what type of equations should be solved?
