### ISSUE TITLE
Excel Merger

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#733]
## Script Title - Excel Merger

**Brief** - Script able to merge 2 or more excels in multiple sheets

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by gitshashwat** [comment]
Sure @pawangeek
