### ISSUE TITLE
Eigen values calculator for 3x3 matrix

### ISSUE THREAD

**Issue by rushil180101** [python-geeks/Automation-scripts#748]
## Eigen Values calculator (for 3x3 matrix)

**Brief** - This script will find 3 eigen values of a given 3x3 matrix if they exist. The program will take the 9 values of a 3x3 matrix line by line and will generate the output showing the characteristic equation and a list of 3 eigen values.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by rushil180101** [comment]
@pawangeek Can you please assign this issue to me?

**Comment by pawangeek** [comment]
> @pawangeek Can you please assign this issue to me?

This is not any general propose automation script
