### ISSUE TITLE
Make a Python3 Program to Scrape ratings for movies and TV Shows

### ISSUE THREAD

**Issue by TJakub** [python-geeks/Automation-scripts#763]
## Script Title - Make a Python3 Program to Scrape ratings for movies and TV Shows

**Brief** - Make a Python3 Program to Scrape ratings for movies and TV Shows

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by walkhenj** [comment]
please assign me this task

**Comment by iahmad16** [comment]
Please assign me this task
