### ISSUE TITLE
Eterm

### ISSUE THREAD

**Issue by Brist0l** [python-geeks/Automation-scripts#806]
## Script Title - Eterm 

**Brief** -
sends emails through the terminal

https://github.com/mrHola21/Eterm
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by oshin94** [comment]
Would be happy to work on it. Kindly assign me the issue.

**Comment by mrHola21** [comment]
I have already made this project . https://github.com/mrHola21/Eterm is my github's repo .
