### ISSUE TITLE
Image Collage 

### ISSUE THREAD

**Issue by Harshak30** [python-geeks/Automation-scripts#807]
## Script Title -
Image Collage using Python
**Brief** -
A script which is used to make 2X2 image collage and the final image can be saved in the system.
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Harshak30** [comment]
@pawangeek  I would like to work on this issue can you please assign it to me.

**Comment by oshin94** [comment]
would be happy to work on it. Kindly assign it to me.

**Comment by dth99** [comment]
> ## Script Title -
> Image Collage using Python **Brief** - A script which is used to make 2X2 image collage and the final image can be saved in the system.
> 
> ## Instructions
> * Create a new folder for your script and file/folder name should be appropriate.
> * Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
> * add requirements.txt if needed
> 
> ### Programming Language
> * [x]  Python
> 
> Happy Coding



> would be happy to work on it. Kindly assign it to me. Hope to get it done in a week.

you can see the example of above explaination in my password manager project https://github.com/dth99/password-manager
