### ISSUE TITLE
Mysqldump to csv

### ISSUE THREAD

**Issue by sre-harine** [python-geeks/Automation-scripts#809]
## Script Title - MySQL dump to csv

**Brief** - Mysqldump is used to generate the logical backup of the MySQL database. It produces the SQL Statements that can be used to recreate the database objects and data. If it is converted into CSV format, it will have the added advantage of being human-readable.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

Kindly assign this issue to me.

**Comment by aharqan** [comment]
Hello, can you please assign this issue to me?

**Comment by ShubhamNagure** [comment]
i'd like to work on it

**Comment by ShubhamNagure** [comment]
Ack, working on it.
