### ISSUE TITLE
Automation for arranging script folders in [a-e], [f-j]...... [u-z]

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#815]
## Script Title - folders_arranger

**Brief** - Currently the number of folders are increased beyond 200. So the script will create 5 folders and arrange in into them

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by TileThePlane** [comment]
Hi, can I work on this? ^^ Thank you.

**Comment by pawangeek** [comment]
> Hi, can I work on this? ^^ Thank you.

Sure Go ahead :)

**Comment by arindamkeswani** [comment]
I would like to work on this issue!

**Comment by rblcoder** [comment]
Hi @pawangeek , I have just started working on this issue in my forked repo https://github.com/rblcoder/Automation-scripts,
once I complete it, is it fine if I create a pull request?

**Comment by pawangeek** [comment]
> Hi @pawangeek , I have just started working on this issue in my forked repo https://github.com/rblcoder/Automation-scripts, once I complete it, is it fine if I create a pull request?

Sure go ahead :)

**Comment by rblcoder** [comment]
Hi @pawangeek , I have created the PR, pull request!
