### ISSUE TITLE
Letter Image Generator

### ISSUE THREAD

**Issue by IsharMhzn** [python-geeks/Automation-scripts#819]
## Script Title - Letter Image Generator

**Brief** - Generate images containing center aligned letters from ("A" to "Z") with random background colors. Similar to that of default google profile picture generator. 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

### Libraries

- [x] PIL

Happy Coding

**Comment by IsharMhzn** [comment]
Its a simple script, I'm not sure if its not done here before. 
If not, **kindly assign the issue to me** :) @pawangeek

**Comment by pawangeek** [comment]
@IsharMhzn No it didn't covered yet, assigning it to you 💯
