### ISSUE TITLE
AutomatedPhoneCalling

### ISSUE THREAD

**Issue by sagnik036** [python-geeks/Automation-scripts#828]
## Script Title -Automated Phone Calling using python
 
**Brief** -
it just a script that help users to automate the calling process by using python, it helps many users to call in bulk so that they can share any particular message with the greatest number of users

### Programming Language

- [x] Python

**Comment by ehildebrandtrojo** [comment]
Hey! Is it alright if you assign me this issue?

Also, just so I'm not mistaken, we are writing a code that takes a message and a list of phone numbers and sends that message to each phone number?
