### ISSUE TITLE
automate security headers and add them in google sheets

### ISSUE THREAD

**Issue by avyayjain** [python-geeks/Automation-scripts#830]
all sites have security headers and we have to keep track of it so i made a script to automate that work

**Comment by ehildebrandtrojo** [comment]
Hey! I'm just starting to get involved in open source and, based on the tags, thought this might be a good place to start. I'm still a bit confused on what needs to be done though. Do you mind elaborating on the task ?

**Comment by pawangeek** [comment]
Hey @avyayjain can you please explain it a Lil bit more

**Comment by avyayjain** [comment]
So there is a site called securityheaders.com where you can check how secure the site is and where does the website lacks so I made a script where you just have to enter the website url and you can check the tags

**Comment by avyayjain** [comment]
can i make a pr for it

**Comment by pawangeek** [comment]
Cool, go ahead

**Comment by avyayjain** [comment]
pls check my pr as it is showing flake8 error and greeting but i have pass it in my code but it is showing error for other codes
