### ISSUE TITLE
Attachment Downloader

### ISSUE THREAD

**Issue by Somanyu** [python-geeks/Automation-scripts#832]
## Attachment Downloader

**An automation script to download attachments from any mail service (Gmail, Yahoo, etc) using imaplib library. It has various constraints that allows us to download specific files on the basis of extensions or file names or sender.** 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by deathsurgeon1** [comment]
Hi @Somanyu , I would like to work on this
