### ISSUE TITLE
Hey, I want to add automatic PC shutdown script.  Please assign this to me.

### ISSUE THREAD

**Issue by Prajwol-Shrestha** [python-geeks/Automation-scripts#833]
## Script Title - Automatic Shutdown

**Brief** -
Automatic shutdown after x time.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by KarthikS373** [comment]
Hey I would like to work on this issue. It would be nice if you can assign this to me...

**Comment by Dani-Google** [comment]
Hi 
I would like to contribute if its still available :)
