### ISSUE TITLE
Speech To Text convertor

### ISSUE THREAD

**Issue by Vicky-Raghuwanshi07** [python-geeks/Automation-scripts#855]
## Script Title -   speech_to_text.py

**Brief** -
An audio will be taken as input and then it will convert it into text using speech_recognition package in Python. The audio duration can be changed from the script, I have set the duration to 5 seconds for now.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding :)

**Comment by pawangeek** [comment]
Hey @Vicky-Raghuwanshi07 [it's already in the repo ](https://github.com/python-geeks/Automation-scripts/tree/main/voice_to_text)

**Comment by Vicky-Raghuwanshi07** [comment]
Yes, the Speech_to_text is there as Audio_to_text but I have a better code
and also have less number line of code (LoC).
