### ISSUE TITLE
Wordle Solver

### ISSUE THREAD

**Issue by Jolinator** [python-geeks/Automation-scripts#861]
## Script Title - Automatic Wordle Solver

**Brief** - I'd like to make a script that automatically opens google and solves Wordle based only on the user's screen

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Jolinator** [comment]
Please assign this to me

**Comment by Faizan96322** [comment]
hey, @pawangeek if @Jolinator is not working on this can you please assign me this task?

**Comment by PRO-GUNE** [comment]
Please assign me to this task. I already have a working version of this task. So I can improve on it

**Comment by StardustRL** [comment]
Hello, we are currently working on a solution for our class project. Can we be assigned to this request and suggest a solution when we will be done ?
