### ISSUE TITLE
Copy to Clipboard

### ISSUE THREAD

**Issue by Prashant-Bhapkar** [python-geeks/Automation-scripts#865]
## Script Title - Copy2Clip

**Brief** - Copying the contents of a text file to the clipboard is an all-too-frequent task, whether it’s a log file someone wants to see, a configuration file you need to share, or even an ssh key. Getting to the file is easy enough on the command line, but then having to open it in an editor just to copy-and-paste takes time you don’t need to waste.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Prashant-Bhapkar** [comment]
Shall I make a PR request by adding the Copy2Clip script?

**Comment by TrainedPro** [comment]
Hello! I would like to work on this. Feel free to assign me to this.

One question that i have. Would you like to run the Python script to be run on a file or how would it function?
