### ISSUE TITLE
XKCD Downloader

### ISSUE THREAD

**Issue by Indrahas** [python-geeks/Automation-scripts#866]
## Script Title -download_xkcd.py

**Brief** -
Code to download the xkcd comics from the internet
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by influous** [comment]
I would like to work on this. Can you please assign this issue to me?
