### ISSUE TITLE
add email slicer script 

### ISSUE THREAD

**Issue by emmydev9** [python-geeks/Automation-scripts#871]
## Script Title -
Email Slicer script
**Brief** -
A script for separating username and domain name from an email address.
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by SainathPoojary** [comment]
Hey @emmydev9, I want to work on this. Can you please assign it to me?

**Comment by kmartin62** [comment]
Putting my name in the hat, I can also do this

**Comment by aarjavpatni** [comment]
Sorry that was by mistake

**Comment by Vivek-raj-gupta-2002** [comment]
I am working on it!!!!

**Comment by Vivek-raj-gupta-2002** [comment]
Please Assign this issue to me I had written the code and just waiting for your approval!!

**Comment by pawangeek** [comment]
Hey @emmydev9, closing this since it's not any kind of automation one will use
