### ISSUE TITLE
Simple GUI Calculator in Python

### ISSUE THREAD

**Issue by visheshdvivedi** [python-geeks/Automation-scripts#883]
Tkinter Calculator

A simple GUI calculator in python using the tkinter library

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

- [x] Python

Please assign me this issue

**Comment by Prakhar9450** [comment]
Please assign the task

**Comment by WaniAthar** [comment]
@visheshdvivedi can i work on this issue?

**Comment by visheshdvivedi** [comment]
@WaniAthar I have already created the code for this project and am ready to create a PR as soon as this issue is assigned to me.

You can view the updated code [here](https://github.com/visheshdvivedi/Automation-scripts/tree/new-branch/tkinter-calculator).

**Comment by bbhoom** [comment]
!assign me

**Comment by bbhoom** [comment]
Please assign me this issue

**Comment by bbhoom** [comment]
!assign me

**Comment by pawangeek** [comment]
Hey @visheshdvivedi it's already added in repo #615
