### ISSUE TITLE
Colour palette generator

### ISSUE THREAD

**Issue by palanioffcl** [python-geeks/Automation-scripts#887]
## Script Title - Colour palatte generator

**Brief** - A simple web app to generate colour palatte using python(flask)

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by mehraankush** [comment]
i can do that but with js.

**Comment by ruchitarpatil001** [comment]
can you assign this issue to me @palanioffcl

**Comment by ruchitarpatil001** [comment]
import colorsys
N = 5
HSV_tuples = [(x*1.0/N, 0.5, 0.5) for x in range(N)]
RGB_tuples = map(lambda x: colorsys.hsv_to_rgb(*x), HSV_tuples)

try this to @palanioffcl

**Comment by MasaakiYagi** [comment]
@palanioffcl 
I have some question about the web-app you want.
- What is input?
When open the web-app, users get randomly colors? Or any settings for generating colors?
- What is output?
Users get listed-colors image? or listed-color codes as text information?

I'd happy to know these requirements from you. Thank you.

@pawangeek 
Could you assign me?

**Comment by ExPl0iT-29** [comment]
Hey,
I have completed the project and other necessary requirements like readme.md and others.
Please Assign me to this task.
I will make a PR when i am assigned to the task.
Thankyou <3
