### ISSUE TITLE
Markdown to pdf

### ISSUE THREAD

**Issue by palanioffcl** [python-geeks/Automation-scripts#888]
## Script Title -markdown to pdf comverter

**Brief** - A simple python script which converts markdown to pdf format

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by jpphilips** [comment]
I wanted to contribute this script to this repo. Can you assign this task to me?

**Comment by ahmedheltaher** [comment]
I am To working on this project, So Can you assign me this issue?
