### ISSUE TITLE
A Script to detect and translate to any language using speech recognition

### ISSUE THREAD

**Issue by Tejaswi-Kumar** [python-geeks/Automation-scripts#889]
## Script Title - Detect and Translate languages with the help of speech recognition

**Brief** -  A python script that first records the user's voice and then converts it to text. After that, it detects the language of the text and then translates the language to the user's desired language, which is asked of the user.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

I wanted to contribute this script to this repo. Can you assign this task to me?
Thanks and regards.

**Comment by jpphilips** [comment]
I wanted to contribute this script to this repo. Can you assign this task to me?
