### ISSUE TITLE
A bot to send memes 

### ISSUE THREAD

**Issue by shy-tan** [python-geeks/Automation-scripts#893]
## Script Title -
Python bot to scrape memes from Reddit and send them in Discord
**Brief** -
An automated bot that sends random mems from r/memes in any Discord sever it is added in.

- The script will first scrape the r/memes subreddit, and then parse the scraped data and store it locally.
- When a pre-defined command is given, the script will send a random meme from the local vault.
- The script also makes sure that there is minimal repetition, that is, the same meme is not sent multiple times. 
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by zmwaris1** [comment]
Assign me this issue, please. I would like to work on this.

**Comment by KartikeyDubeyKD** [comment]
Hey, I'm interested in working on this issue. Can you please assign this to me?

**Comment by shy-tan** [comment]
I was working on this.

**Comment by KartikeyDubeyKD** [comment]
ok
