### ISSUE TITLE
Failing to run - Pomodoro Timer

### ISSUE THREAD

**Issue by hexmatrix** [python-geeks/Automation-scripts#894]
Good day,

I was enjoying looking through GitHub to help me with some day-to-day automation.

I am a student so thought that the Pomodoro Timer looked as though it would be a good idea for studying.

However, when I came to try and run the program; as I am using a MacBook Pro, it would not run. I particularly say that the only error that is present is that there is no module "winsound" which is quite obviously a windows library. 

It would be nice for this timer to be cross-platform. I'm not sure the best way to do that, but I'm sure it can be done. 

Thanks for listening,
Danny.

**Comment by rohanprichard** [comment]
Hi, I have solved this issue. Can I please be assigned to it?

**Comment by hexmatrix** [comment]
Hi @rohanprichard. Thank you for resolving the issue. I'm not sure how to assign you to it, but perhaps an admin can? 

Thanks,
Danny.

**Comment by rohanprichard** [comment]
@hexmatrix I didn't create a PR yet, since the rules said that you have to be assigned to an issue before doing that. I just noticed that you assigned someone, which is why I asked you
