### ISSUE TITLE
Extract text from a PDF

### ISSUE THREAD

**Issue by devikabhapkar** [python-geeks/Automation-scripts#899]
## Script Title -  Extract text from a PDF

**Brief** -
Python can also be used to easily extract text from PDFs using the PyPDF2 package. Getting text from a PDF file proves useful for data mining, invoice reconciliation, or report generation, and the extraction process can be automated in just a few lines of code.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by hectorpasarin** [comment]
I would like to work in this issue. Couldnyou assign It to me.
Thanks

**Comment by ibrahim-ogunbiyi** [comment]
Can you please assign this issue to me? Thank you

**Comment by pawangeek** [comment]
Closed by #900
