### ISSUE TITLE
Empty Recycle Bin

### ISSUE THREAD

**Issue by niirmaaltwaatii** [python-geeks/Automation-scripts#904]
## Empty Recycle Bin

**Brief** 
Running the Script will Empty the Recycle Bin

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by jpphilips** [comment]
Pls assign this to me

**Comment by zys989** [comment]
plz assign it to me, Thx!!:blush:

**Comment by diegooldenburg** [comment]
please assign, I am prepared to make a PR

**Comment by SpandyBoss** [comment]
Hi, I'm new and willing to make my first contribution, kindly assign this task to me.
Thanks.
