### ISSUE TITLE
Speedtest

### ISSUE THREAD

**Issue by Hugo-UCL** [python-geeks/Automation-scripts#909]
## Script Title - Speedtest

**Brief** - This python script allows you to dispense with online speedtests. The script notify the ping, the wifi upload speed, and the download speed to get an opinion on your Internet connection.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Hugo-UCL** [comment]
Please let me know what the situation is so that I can contribute. Thank you !
@pawangeek

**Comment by Ash0069** [comment]
Hi @pawangeek, please assign this issue to me and maybe me and @Hugo-UCL will be able to solve it faster together
