### ISSUE TITLE
aes encryption- decryption 

### ISSUE THREAD

**Issue by kaliappan01** [python-geeks/Automation-scripts#927]
## aes_py -

**This script will be able to encrypt and decrypt text using AES256 using password based key.** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kaliappan01** [comment]
please assign this to me

**Comment by MasaakiYagi** [comment]
Hi, I wish to code this function!
Could you assign me??

**Comment by Sahilll15** [comment]
can you assign this to me .

**Comment by ptiwari6239** [comment]
hye, if no one is working can i work on this ?
