### ISSUE TITLE
Open AI Bot

### ISSUE THREAD

**Issue by sehgalspandan** [python-geeks/Automation-scripts#931]
## Script Title - Ai bot 

**A python script which will take user's input and it will use OpenAi to get results accordingly. It can be used for any purpose from generating blog posts to explaining code!** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by prathameshdol196** [comment]
hey mate I have created bots before and I'm sure that I can do this as well but I'm new to open source so please assign this task to me

**Comment by mahir118** [comment]
Hi, is this issue still available?

**Comment by SpandyBoss** [comment]
Yes its

**Comment by mahir118** [comment]
Thanks for letting me know @SpandyBoss. Can you please help me with the initial steps as I am new to Open Source Contributions.

**Comment by SpandyBoss** [comment]
I'm too new to open source @mahir118 and sorry to but I'm not aware about that, I thought I had to do it on my own, if you want me to assign you I can, and if you mean "that what to build in this issue" by "Initial Steps" then I can guide you through.

Thanks

**Comment by ShlokJswl** [comment]
@SpandyBoss Hi can you please assign this issue to me, I'll try to solve this.

**Comment by ShlokJswl** [comment]
Hi @SpandyBoss i have gone through it, if you can assign this to me i can start working on it.

**Comment by SpandyBoss** [comment]
> Hi @SpandyBoss i have gone through it, if you can assign this to me i can start working on it.

Hi, @ShlokJswl as I also mentioned in one of the threads, I don't know how to assign issues, I thought I would create this on mu own.. I'm new to open source . If you have knowledge on how I can assign this issue to you kindly guide me through it I'll then look into it.

Thanks 😊

**Comment by ShlokJswl** [comment]
> > Hi @SpandyBoss i have gone through it, if you can assign this to me i can start working on it.
> 
> Hi, @ShlokJswl as I also mentioned in one of the threads, I don't know how to assign issues, I thought I would create this on mu own.. I'm new to open source . If you have knowledge on how I can assign this issue to you kindly guide me through it I'll then look into it.
> 
> Thanks 😊

**Comment by ShlokJswl** [comment]
> > Hi @SpandyBoss i have gone through it, if you can assign this to me i can start working on it.
> 
> Hi, @ShlokJswl as I also mentioned in one of the threads, I don't know how to assign issues, I thought I would create this on mu own.. I'm new to open source . If you have knowledge on how I can assign this issue to you kindly guide me through it I'll then look into it.
> 
> Thanks 😊

Hi @SpandyBoss maybe you can view this git document once? https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#  Thank you.

**Comment by SpandyBoss** [comment]
> > > Hi @SpandyBoss i have gone through it, if you can assign this to me i can start working on it.
> > 
> > Hi, @ShlokJswl as I also mentioned in one of the threads, I don't know how to assign issues, I thought I would create this on mu own.. I'm new to open source . If you have knowledge on how I can assign this issue to you kindly guide me through it I'll then look into it.
> > 
> > Thanks 😊
> 
> Hi @SpandyBoss maybe you can view this git document once? https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#  Thank you. 
> 
> 

I've gone through this ... I think that I don't have the write permission to the repo that's the reason maybe ...

Thanks

**Comment by SpandyBoss** [comment]
Yea sure, go ahead

**Comment by SpandyBoss** [comment]
> > > > > Hi @SpandyBoss i have gone through it, if you can assign this to me i can start working on it.
> > > > 
> > > > 
> > > > Hi, @ShlokJswl as I also mentioned in one of the threads, I don't know how to assign issues, I thought I would create this on mu own.. I'm new to open source . If you have knowledge on how I can assign this issue to you kindly guide me through it I'll then look into it.
> > > > Thanks 😊
> > > 
> > > 
> > > Hi @SpandyBoss maybe you can view this git document once? https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#  Thank you.
> > 
> > I've gone through this ... I think that I don't have the write permission to the repo that's the reason maybe ...
> > 
> > Thanks
> 
> OH okay i understand but do i have your approval to work on this issue?

Yea sure, go ahead

**Comment by Royce123882** [comment]
Hi, is this still available?

**Comment by shrivastavanolo** [comment]
Hi @SpandyBoss. Please assign this to me if it's still available. Thanks!

**Comment by RohanIyer136** [comment]
Hi @sehgalspandan can you please assign me to this issue. I am also new to open source but would love to contribute and try this out

Thanks and regards

**Comment by rafaelnwitter** [comment]
@pawangeek is this still available?

**Comment by O-sama12** [comment]
@prathameshdol196 Hi, please help me as I'm new to open source contribution.

**Comment by Davda-James** [comment]
If this is still open please assign this task to me, I have done it, so that I can raise a PR for this issue.
