### ISSUE TITLE
Other Video format to .mp4 converter

### ISSUE THREAD

**Issue by shrivastavanolo** [python-geeks/Automation-scripts#944]
## Script Title - video_to_mp4

**Brief** - Create a script to convert any of the following file formats - [".flv",".avi",".mov"] to ".mp4"

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by AdriaGual** [comment]
Hey there!

I've gone ahead and created a pull request for issue #944: [PR 946](https://github.com/python-geeks/Automation-scripts/pull/946).

Would it be possible to assign this issue to me?

Thanks a bunch!

**Comment by bugbreaker18** [comment]
Hi. Is this issue still open? 
if yes.. then i would like to work on the same.

**Comment by safimuhammad** [comment]
hello is this issue still open, I'd like to work on this.

**Comment by kirtirawal** [comment]
Hi folks It will be helpful I would like work on the issue

**Comment by python-fuse** [comment]
Yooooo

I really wanna work on this issue
