### ISSUE TITLE
Weather notifier 🌤️

### ISSUE THREAD

**Issue by aryanmeh624** [python-geeks/Automation-scripts#954]
## Script Title -Weather notifier!

**Brief** -
The notifier uses openweathermap api and tells you the weather forecast of the day based on your location. built using tkinter for GUI experience. Can run in background with option to run it in after a fixed interval.
## Instructions

- Mention your location.
- Mention if you want the script to run after a fixed interval or on click only.

### Programming Language

- [x] Python

Happy Coding

**Comment by BDadmehr0** [comment]
Hello, I would like to work on these issues, but when I checked openweathermap, its APIs were paid. If you don't have a problem, I will use the free weather service.

**Comment by aryanmeh624** [comment]
oh sorry  I think I messed up I want to do it and wanted the creator of this repo to assign it to me so I can build it and create a pull request.

**Comment by aryanmeh624** [comment]
What is the procedure of doing that. What I understood from the contribute.md was that for me to build an automation script i need to mae an issue and wait for the author to assign it to me.

**Comment by BDadmehr0** [comment]
> What is the procedure of doing that. What I understood from the contribute.md was that for me to build an automation script i need to mae an issue and wait for the author to assign it to me.

oh sorry If you want to work on these issues alone, there is no problem

**Comment by aryanmeh624** [comment]
i dont mind collaborating its my first open source comntribution though i have some experience with tinter and python.Let me now if you wanna collaborate.
