### ISSUE TITLE
Flake8 lint error from irrelevant scripts occurred on some pull requests

### ISSUE THREAD

**Issue by quinn-sasha** [python-geeks/Automation-scripts#956]
**Describe the bug**

Flake 8 lint warning from `pdf_watermarkadder` and `video_cropper`.
- `pdf_watermarkadder`: missing whitespace after ',' on line 26 of main.py.
- `video_cropper`: Didn't use isinstance() for checking if an object is an instance of a class or type

**To Reproduce**
1. Create virtual environment and activate it
2. `pip install flake8`
3. Go to `pdf_watermarkadder` (or `video_cropper`) folder
4. `flake8 main.py` (if you are in `video_cropper`, `flake8 video_cropper.py`)
5. See error

**Expected behavior**

My pull request should  pass flake8 lint check.

**Screenshots**

![image](https://github.com/user-attachments/assets/a8701d98-1358-4efc-b64f-bc1c46eff45e)

**Additional context**

**Comment by Davda-James** [comment]
Yes this is true today I have made a PR adding another script and there is no error in my script in linting but due to already existing scripts linting issue the linker check is failed.

**Comment by pawangeek** [comment]
@Davda-James @quinn-sasha It's solved now, either make a dummy commit or fresh PR to run this, closed by #974
