### ISSUE TITLE
Automated Quiz Generator from Folder Files for Personalized Practice

### ISSUE THREAD

**Issue by NamanVer02** [python-geeks/Automation-scripts#966]
## Script Title - Automated Quiz Generator from Folder Files for Personalized Practice

**Brief** - This script automates the process of generating quizzes by extracting content from PDF files stored in a specified folder. It uses a large language model (LLM) to intelligently analyze the text, formulate questions, and generate a quiz based on the extracted information. The generated quiz is saved as a text document, making it easy for users to review and practice the material. This tool is ideal for educators, students, or anyone looking to create personalized quizzes from their study materials.

**More Features** 
- Support for More File Formats
- GUI-Based Quiz Interface
- Multiple Question Types

**User Requirements**
- GROG API Key for the LLM (free)
- Source Files

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by C0DE-SLAYER** [comment]
i want to contribute . plz assign me thank you

**Comment by swathihameed** [comment]
I am interested in contributing. Please let me know if I can help.

**Comment by NamanVer02** [comment]
I am really glad people are willing to contribute to this script, but I already have it ready and I am waiting for the issue to be assigned to me. I love to add your contributions once the core script is merged. Thank you :)

**Comment by sanjogbhalla16** [comment]
I am interested in contributing. Please let me know if there is something I can help with. Thank you :)

**Comment by NamanVer02** [comment]
@pawangeek I added the script as a pull request. Could you please check and let me know if more changes are required before merging it. Thank you.
