### ISSUE TITLE
New Script: UV Index and Sunscreen Advice

### ISSUE THREAD

**Issue by Dd1235** [python-geeks/Automation-scripts#971]
## UV Index and Sunscreen Advice

**Brief** -
The script will take the user’s location as input , fetch the current UV index from an API, and provide personalized sunscreen advice based on UV exposure, whether the user is indoors or outdoors, and suggest the appropriate SPF if sunscreen is recommended.

### Programming Language

- [x] Python

**Comment by laksh-krishna-sharma** [comment]
Hi @Dd1235, may i work on this issue with a bit of your guidance

**Comment by bao1311** [comment]
Hey may I ask what 1 task done is?

**Comment by Rupesh-Singh-Karki** [comment]
Hii @Dd1235, may i work on this issue with a bit of your guidance.
