### ISSUE TITLE
want to add the new script that detect language 

### ISSUE THREAD

**Issue by tusharmishra069** [python-geeks/Automation-scripts#972]
## Script Title - Detect the Language 

**Brief** - in the script i use the python to get the detection , that is given text is in which language .
i use the the python lib to do this

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by tusharmishra069** [comment]
.take

**Comment by tusharmishra069** [comment]
kindly assign me i love to work on this

**Comment by laksh-krishna-sharma** [comment]
Hello @tusharmishra069  may i work on this issue with a bit of your guidance
