### ISSUE TITLE
New Script: A File Organizer script to organize files based on file types.

### ISSUE THREAD

**Issue by Rohit-Sharma-RS** [python-geeks/Automation-scripts#984]
## Script Title - A file Organizer script

**Brief** -
- The script will ask for a directory path.
- It will scan the directory for files.
- It will create subdirectories based on file types (e.g., Images, Documents, Videos).
- It will move the files into their corresponding subdirectories.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Rohit-Sharma-RS** [comment]
Hi! I am working on this project right now.

**Comment by pawangeek** [comment]
Hey @Rohit-Sharma-RS It's already added in #220
